In [2]:
import pandas as pd
import glob
import re

In [4]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/notebooks/scraping/matches_past2.csv')

df

,date,home_team,away_team,home_score,away_score,match_id,link
0,Saturday Mar 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
1,Saturday Mar 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
2,Saturday Mar 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
3,Saturday Mar 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
4,Saturday Mar 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
5,Saturday Mar 7,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
6,Saturday Mar 7,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
7,Saturday Mar 7,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
8,Saturday Mar 7,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
9,Saturday Mar 7,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
10,Saturday Mar 7,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
11,Saturday Mar 7,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
12,Sunday Mar 8,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
13,Sunday Mar 8,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
14,Saturday Feb 28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
15,Saturday Feb 28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
16,Saturday Feb 28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
17,Saturday Feb 28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
18,Saturday Feb 28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
19,Saturday Feb 28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
20,Saturday Feb 28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
21,Saturday Feb 28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
22,Saturday Feb 28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
23,Saturday Feb 28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
24,Saturday Feb 28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
25,Sunday Mar 1,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
26,Sunday Mar 1,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
27,Sunday Mar 1,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
28,Sunday Mar 1,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
29,Saturday Feb 21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
30,Saturday Feb 21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
31,Saturday Feb 21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
32,Saturday Feb 21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
33,Saturday Feb 21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
34,Saturday Feb 21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
35,Saturday Feb 21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
36,Saturday Feb 21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
37,Saturday Feb 21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
38,Saturday Feb 21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
39,Saturday Feb 21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
40,Saturday Feb 21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
41,Saturday Feb 21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
42,Sunday Feb 22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
43,Sunday Feb 22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [6]:
month_map = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12",
        'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06', 'jul': '07', 
        'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12'
    }

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

df['date'] = df['date'].apply(lambda x: ' '.join([word for word in x.split() if word not in days]))

df['date'] = df['date'].str.split('\n').str[0]

df['date'] = df['date'].apply(
        lambda x: re.sub(
            r"([A-Za-z]+)",
            lambda m: month_map[m.group(1).lower()],
            x
        )
    )

df['date'] = df['date'].apply(lambda x: x + " 2026" if re.search(r"\d{4}$", x) is None else x)

df['date'] = pd.to_datetime(df['date'], format="%m %d %Y")

In [7]:
df

,date,home_team,away_team,home_score,away_score,match_id,link
0,2026-03-07,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
1,2026-03-07,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
2,2026-03-07,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
3,2026-03-07,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
4,2026-03-07,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
5,2026-03-07,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
6,2026-03-07,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
7,2026-03-07,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
8,2026-03-07,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
9,2026-03-07,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
10,2026-03-07,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
11,2026-03-07,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
12,2026-03-08,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
13,2026-03-08,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
14,2026-02-28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
15,2026-02-28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
16,2026-02-28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
17,2026-02-28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
18,2026-02-28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
19,2026-02-28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
20,2026-02-28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
21,2026-02-28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
22,2026-02-28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
23,2026-02-28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
24,2026-02-28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
25,2026-03-01,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
26,2026-03-01,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
27,2026-03-01,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
28,2026-03-01,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
29,2026-02-21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
30,2026-02-21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
31,2026-02-21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
32,2026-02-21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
33,2026-02-21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
34,2026-02-21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
35,2026-02-21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
36,2026-02-21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
37,2026-02-21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
38,2026-02-21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
39,2026-02-21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
40,2026-02-21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
41,2026-02-21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
42,2026-02-22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
43,2026-02-22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [ ]:
df = df.drop(columns=['link'])

KeyError: "['link'] not found in axis"

In [11]:
df

         date home_team away_team  home_score  away_score  match_id
0  2026-03-07       NYC       ORL           5           0  8865ae2a
1  2026-03-07        DC       MIA           1           2  0c956f37
2  2026-03-07       ATL       RSL           2           3  b0713dc5
3  2026-03-07       CLT       ATX           3           1  646c3889
4  2026-03-07       CLB       CHI           0           0  5291010f
5  2026-03-07       PHI        SJ           0           1  3991a1bb
6  2026-03-07       SKC        SD           0           1  f1fd2f24
7  2026-03-07       NSH       MIN           3           1  dbcc55cf
8  2026-03-07       STL       SEA           0           1  29662ef7
9  2026-03-07       COL        LA           4           1  e8e41c6d
10 2026-03-07      LAFC       DAL           1           0  ab677e15
11 2026-03-07       POR       VAN           1           4  679970bf
12 2026-03-08      RBNY       MTL           0           3  bc090e7f
13 2026-03-08       CIN       TOR           0           1  1d8589b6
14 2026-02-28       CHI       MTL           3           0  2677b200
15 2026-02-28      RBNY        NE           1           0  696e062e
16 2026-02-28       COL       POR           2           0  9932553a
17 2026-02-28       MIN       CIN           1           0  ccc1ebe1
18 2026-02-28       RSL       SEA           2           1  c123bdf2
19 2026-02-28        SJ       ATL           2           0  5924fd44
20 2026-02-28       DAL       NSH           0           0  19a7b817
21 2026-02-28       HOU      LAFC           0           2  a52dabed
22 2026-02-28       SKC       CLB           2           2  775e1f69
23 2026-02-28       VAN       TOR           3           0  68a62bb0
24 2026-02-28        LA       CLT           3           0  708a4133
25 2026-03-01       ATX        DC           1           0  ce9a56f3
26 2026-03-01       PHI       NYC           1           2  fdf75599
27 2026-03-01       ORL       MIA           2           4  99726934
28 2026-03-01        SD       STL           2           0  8317cb19
29 2026-02-21       STL       CLT           1           1  95ee8e18
30 2026-02-21       CIN       ATL           2           0  3fe21bbf
31 2026-02-21        DC       PHI           1           0  0c970002
32 2026-02-21       ORL      RBNY           1           2  36ada33a
33 2026-02-21       VAN       RSL           1           0  31608e02
34 2026-02-21       ATX       MIN           2           2  adfb093f
35 2026-02-21       DAL       TOR           3           2  f45d88a5
36 2026-02-21       HOU       CHI           2           1  ed610e2c
37 2026-02-21       NSH        NE           4           1  1a13ae26
38 2026-02-21      LAFC       MIA           3           0  b5d3f6dd
39 2026-02-21       POR       CLB           3           2  a2d28725
40 2026-02-21        SD       MTL           5           0  e138c719
41 2026-02-21        SJ       SKC           3           0  9a5ab6be
42 2026-02-22        LA       NYC           1           1  f6e2b863
43 2026-02-22       SEA       COL           2           0  890188eb

In [12]:
df.to_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/matches_past_cleaned_0326.csv', index=False)

In [3]:
files = glob.glob("G:/My Drive/GitHubProjects/MLS/data/raw/matches/feed/*.csv")

In [6]:
from datetime import datetime, timedelta
import os
import re

In [8]:
### concat all files that start with "feed" and were made today

dfs = []

yesterday = datetime.now().date() - timedelta(days=2)

for file in files:
    if re.search(r"\\feed.*\.csv", file):
        modified = datetime.fromtimestamp(os.path.getmtime(file)).date()
        if modified == yesterday:
            df = pd.read_csv(file, dtype={'match_id': str})
            dfs.append(df)

df = pd.concat(dfs, ignore_index=True)

In [9]:
df

,match_id,date,minute,title,comment,out_player,in_player
0,5c78a593,Sunday February 22\nDignity Health Sports Park,NaN,FULL TIME,"Second half ends, LA Galaxy 1, New York City F...",NaN,NaN
1,5c78a593,Sunday February 22\nDignity Health Sports Park,NaN,END OF SECOND HALF,End of match.,NaN,NaN
2,5c78a593,Sunday February 22\nDignity Health Sports Park,90'+2,Attempt Missed,Attempt missed. Nicolás Fernández's (New York ...,NaN,NaN
3,5c78a593,Sunday February 22\nDignity Health Sports Park,90',Attempt Saved,Attempt saved. Joseph Paintsil's (LA Galaxy) w...,NaN,NaN
4,5c78a593,Sunday February 22\nDignity Health Sports Park,88',NaN,NaN,H. Wolf,T. Magno
...,...,...,...,...,...,...,...
1782,6afff6a7,Saturday March 7\nYankee Stadium,12',Attempt Missed,Keaton Parks (New York City Football Club) wit...,NaN,NaN
1783,6afff6a7,Saturday March 7\nYankee Stadium,10',Attempt Saved,Attempt blocked. Tyrese Spicer's (Orlando City...,NaN,NaN
1784,6afff6a7,Saturday March 7\nYankee Stadium,7',Yellow Card,Tahir Reid-Brown (Orlando City) is shown the y...,NaN,NaN
1785,6afff6a7,Saturday March 7\nYankee Stadium,3',Attempt Missed,Attempt missed. Nicolás Fernández's (New York ...,NaN,NaN
1786,6afff6a7,Saturday March 7\nYankee Stadium,NaN,KICK OFF,First half begins.,NaN,NaN

In [258]:
df['date'] = df['date'].str.split('\n').str[0]

In [259]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [260]:
month_map = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12",
        "jan": "01", "feb": "02", "mar": "03", "apr": "04",
        "jun": "06", "jul": "07", "aug": "08",
        "sep": "09", "oct": "10", "nov": "11", "dec": "12"
    }

In [229]:
df

,match_id,date,minute,title,comment,out_player,in_player
0,6afff6a7,Saturday March 7,NaN,FULL TIME,"Second half ends, New York City Football Club ...",NaN,NaN
1,6afff6a7,Saturday March 7,NaN,END OF SECOND HALF,End of match.,NaN,NaN
2,6afff6a7,Saturday March 7,87',NaN,NaN,N. Fernández,S. Reid
3,6afff6a7,Saturday March 7,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN
4,6afff6a7,Saturday March 7,78',NaN,NaN,M. Pašalić,Tiago
...,...,...,...,...,...,...,...
1782,7631e105,Sunday February 22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN
1783,7631e105,Sunday February 22,8',NaN,NaN,J. Morris,P. Rothrock
1784,7631e105,Sunday February 22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN
1785,7631e105,Sunday February 22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN
1786,7631e105,Sunday February 22,NaN,KICK OFF,First half begins.,NaN,NaN

In [230]:
### find float in date strings

float_dates = df[df["date"].apply(lambda x: isinstance(x, float))]
float_dates

Empty DataFrame
Columns: [match_id, date, minute, title, comment, out_player, in_player]
Index: []

In [186]:
## fill match id f0b7242e with date "Saturday Aug 31, 2024"

df.loc[df['match_id'] == 'f0b7242e', 'date'] = 'Saturday Aug 31, 2024'

### fill match id 3c29cb63 with Saturday Aug 24, 2024

df.loc[df['match_id'] == '3c29cb63', 'date'] = 'Saturday Aug 24, 2024'

### fill match id bec23bed with Saturday Sep 20

df.loc[df['match_id'] == 'bec23bed', 'date'] = 'Saturday Sep 20'

In [187]:
## drop row # 16194 

df = df.drop(index=16194)

KeyError: '[16194] not found in axis'

In [ ]:
### find float in date strings

float_dates2 = df[df["date"].apply(lambda x: isinstance(x, float))]
float_dates2

Empty DataFrame
Columns: [match_id, date, minute, title, comment, out_player, in_player]
Index: []

In [261]:
## remove day names from date strings

df['date'] = df['date'].apply(lambda x: ' '.join([word for word in x.split() if word not in days]))

In [263]:
df['date'] = df['date'].apply(
        lambda x: re.sub(
            r"([A-Za-z]+)",
            lambda m: month_map[m.group(1).lower()],
            x
        )
    )

df['date'] = df['date'].apply(lambda x: x + " 2026" if re.search(r"\d{4}$", x) is None else x)

### remove , from date strings

df['date'] = df['date'].apply(lambda x: x.replace(',', ''))

In [264]:
#### convert date column to datetime from mm dd yyyy format

df['date'] = pd.to_datetime(df['date'], format="%m %d %Y")

In [265]:
## if corner in comment, then title is corner

df['title'] = df.apply(lambda x: 'Corner' if pd.notna(x['comment']) and 'corner' in x['comment'].lower() else x['title'], axis=1)

df['title'] = df.apply(lambda x: 'Foul' if pd.notna(x['comment']) and 'foul' in x['comment'].lower() else x['title'], axis=1)

df['title'] = df.apply(lambda x: 'Offside' if pd.notna(x['comment']) and 'offside' in x['comment'].lower() else x['title'], axis=1)

In [ ]:
clubs = [
    "Atlanta United",
    "Austin FC",
    "CF Montréal",
    "Charlotte FC",
    "Chicago Fire FC",
    "FC Cincinnati",
    "Colorado Rapids",
    "Columbus Crew",
    "D.C. United",
    "FC Dallas",
    "Houston Dynamo FC",
    "Sporting Kansas City",
    "LA Galaxy",
    "Los Angeles Football Club",
    "Inter Miami CF",
    "Minnesota United FC",
    "Minnesota United",
    "Nashville SC",
    "New England Revolution",
    "New York City Football Club",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City",
    "Philadelphia Union",
    "Portland Timbers",
    "Real Salt Lake",
    "San Diego FC",
    "San Jose Earthquakes",
    "Seattle Sounders FC",
    "St. Louis CITY SC",
    "Toronto FC",
    "Vancouver Whitecaps FC"
]

team_map = {
    "Atlanta United": "ATL",
    "Austin FC": "ATX",
    "CF Montréal": "MTL",
    "Charlotte FC": "CLT",
    "Chicago Fire FC": "CHI",
    "FC Cincinnati": "CIN",
    "Colorado Rapids": "COL",
    "Columbus Crew": "CLB",
    "D.C. United": "DC",
    "FC Dallas": "DAL",
    "Houston Dynamo FC": "HOU",
    "Sporting Kansas City": "SKC",
    "LA Galaxy": "LA",
    "Los Angeles Football Club": "LAFC",
    "Inter Miami CF": "MIA",
    "Minnesota United": "MIN",
    "Minnesota United FC": "MIN",
    "Nashville SC": "NSH",
    "New England Revolution": "NE",
    "New York City Football Club": "NYC",
    "New York City FC": "NYC",
    "New York Red Bulls": "RBNY",
    "Orlando City": "ORL",
    "Philadelphia Union": "PHI",
    "Portland Timbers": "POR",
    "Real Salt Lake": "RSL",
    "San Diego FC": "SD",
    "San Jose Earthquakes": "SJ",
    "Seattle Sounders FC": "SEA",
    "St. Louis CITY SC": "STL",
    "Toronto FC": "TOR",
    "Vancouver Whitecaps FC": "VAN"
}




def assign_teams_from_fulltime(df):
    df = df.copy()

    # create output columns
    df["home_team"] = None
    df["away_team"] = None

    # Improved regex: allow apostrophes, accents, FC, SC, etc.
    pattern = re.compile(
        r"Second half ends,\s*([A-Za-zÀ-ÿ .'-]+?)\s+\d+,\s*([A-Za-zÀ-ÿ .'-]+?)\s+\d+",
        re.IGNORECASE
    )

    for mid, group in df.groupby("match_id"):

        ft = group[group["title"].str.contains("FULL TIME", case=False, na=False)]

        if len(ft) == 0:
            continue

        comment = ft.iloc[0]["comment"]

        match = pattern.search(comment)
        if not match:
            continue

        home_full = match.group(1).strip()
        away_full = match.group(2).strip()

        # 1. Exact match
        home_short = team_map.get(home_full)
        away_short = team_map.get(away_full)

        # 2. If exact match failed, try fuzzy match from clubs list
        if home_short is None:
            for club in clubs:
                if club.lower() in home_full.lower():
                    home_short = team_map.get(club)
                    break

        if away_short is None:
            for club in clubs:
                if club.lower() in away_full.lower():
                    away_short = team_map.get(club)
                    break

        # 3. Final fallback → None
        # (Later you can log missing clubs if needed)

        df.loc[df.match_id == mid, "home_team"] = home_short
        df.loc[df.match_id == mid, "away_team"] = away_short

    return df

In [38]:
df = assign_teams_from_fulltime(df)

In [266]:
df

,match_id,date,minute,title,comment,out_player,in_player
0,6afff6a7,2026-03-07,NaN,FULL TIME,"Second half ends, New York City Football Club ...",NaN,NaN
1,6afff6a7,2026-03-07,NaN,END OF SECOND HALF,End of match.,NaN,NaN
2,6afff6a7,2026-03-07,87',NaN,NaN,N. Fernández,S. Reid
3,6afff6a7,2026-03-07,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN
4,6afff6a7,2026-03-07,78',NaN,NaN,M. Pašalić,Tiago
...,...,...,...,...,...,...,...
1782,7631e105,2026-02-22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN
1783,7631e105,2026-02-22,8',NaN,NaN,J. Morris,P. Rothrock
1784,7631e105,2026-02-22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN
1785,7631e105,2026-02-22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN
1786,7631e105,2026-02-22,NaN,KICK OFF,First half begins.,NaN,NaN

In [40]:
### check for na teams

df[df['home_team'].isna() | df['away_team'].isna()]

,match_id,date,minute,title,comment,out_player,in_player,home_team,away_team
484,c1d67317,2026-03-08,NaN,END OF SECOND HALF,End of match.,NaN,NaN,None,MTL
485,c1d67317,2026-03-08,NaN,FULL TIME,"Second half ends, Red Bull New York 0, CF Mont...",NaN,NaN,None,MTL
486,c1d67317,2026-03-08,90'+3,Attempt Saved,Attempt saved. Roald Mitchell's (Red Bull New ...,NaN,NaN,None,MTL
487,c1d67317,2026-03-08,90',Attempt Missed,Attempt missed. Noah Streit's (CF Montréal) wi...,NaN,NaN,None,MTL
488,c1d67317,2026-03-08,88',Attempt Missed,Attempt missed. Juan Mina's (Red Bull New York...,NaN,NaN,None,MTL
...,...,...,...,...,...,...,...,...,...
1359,d2984702,2026-02-21,12',Attempt Saved,Attempt saved. Jorge Ruvalcaba's (Red Bull New...,NaN,NaN,ORL,None
1360,d2984702,2026-02-21,8',GOAL,Goal! 0:1. Julian Hall (Red Bull New York) sco...,NaN,NaN,ORL,None
1361,d2984702,2026-02-21,5',Attempt Saved,Attempt saved. Cade Cowell's (Red Bull New Yor...,NaN,NaN,ORL,None
1362,d2984702,2026-02-21,5',Attempt Missed,Julian Hall (Red Bull New York) with right foo...,NaN,NaN,ORL,None
1363,d2984702,2026-02-21,NaN,KICK OFF,First half begins.,NaN,NaN,ORL,None

In [18]:
### delete na team rows

df = df[~(df['home_team'].isna() | df['away_team'].isna())]

In [267]:
### delete row is 'lineups' is in comment

df = df[~df['comment'].str.contains('Lineups', na=False)]

df = df[~df['title'].str.contains('KICK OFF|HALF TIME|FULL TIME|END OF SECOND HALF', na=False)]

In [268]:
df

,match_id,date,minute,title,comment,out_player,in_player
2,6afff6a7,2026-03-07,87',NaN,NaN,N. Fernández,S. Reid
3,6afff6a7,2026-03-07,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN
4,6afff6a7,2026-03-07,78',NaN,NaN,M. Pašalić,Tiago
5,6afff6a7,2026-03-07,71',NaN,NaN,K. Parks,R. Gustavo
6,6afff6a7,2026-03-07,71',NaN,NaN,A. Ojeda,M. Carrizo
...,...,...,...,...,...,...,...
1781,7631e105,2026-02-22,13',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN
1782,7631e105,2026-02-22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN
1783,7631e105,2026-02-22,8',NaN,NaN,J. Morris,P. Rothrock
1784,7631e105,2026-02-22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN
1785,7631e105,2026-02-22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN

In [269]:
## if minute is missing, delete

df = df[df['minute'].notna()]

In [270]:
df

,match_id,date,minute,title,comment,out_player,in_player
2,6afff6a7,2026-03-07,87',NaN,NaN,N. Fernández,S. Reid
3,6afff6a7,2026-03-07,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN
4,6afff6a7,2026-03-07,78',NaN,NaN,M. Pašalić,Tiago
5,6afff6a7,2026-03-07,71',NaN,NaN,K. Parks,R. Gustavo
6,6afff6a7,2026-03-07,71',NaN,NaN,A. Ojeda,M. Carrizo
...,...,...,...,...,...,...,...
1781,7631e105,2026-02-22,13',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN
1782,7631e105,2026-02-22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN
1783,7631e105,2026-02-22,8',NaN,NaN,J. Morris,P. Rothrock
1784,7631e105,2026-02-22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN
1785,7631e105,2026-02-22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN

In [240]:
### reverse minute sorting

print(df['match_id'].dtype)
df = df.iloc[::-1].reset_index(drop=True)
print(df['match_id'].dtype)

object
object

In [241]:
print(df['match_id'].iloc[-1])
print(df['match_id'].iloc[1])

6afff6a7
7631e105

In [242]:
bad_files = []
for file in files:
    if re.search(r"^feed.*\.csv", os.path.basename(file)):
        temp = pd.read_csv(file, dtype={'match_id': str})
        if temp['match_id'].str.contains(r'e\+', na=False).any():
            bad_files.append(file)

print(f"Found {len(bad_files)} bad files:")
for f in bad_files:
    print(f)

Found 0 bad files:

In [271]:
### if title is missing, fill with 'Substitution' 
df['title'] = df['title'].fillna('Substitution')

### move in_player and out_player to comment if title is Substitution
df['comment'] = df.apply(lambda x: f"Substitution: {x['out_player']} out, {x['in_player']} in" if x['title'] == 'Substitution' else x['comment'], axis=1)

In [272]:
df

,match_id,date,minute,title,comment,out_player,in_player
2,6afff6a7,2026-03-07,87',Substitution,"Substitution: N. Fernández out, S. Reid in",N. Fernández,S. Reid
3,6afff6a7,2026-03-07,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN
4,6afff6a7,2026-03-07,78',Substitution,"Substitution: M. Pašalić out, Tiago in",M. Pašalić,Tiago
5,6afff6a7,2026-03-07,71',Substitution,"Substitution: K. Parks out, R. Gustavo in",K. Parks,R. Gustavo
6,6afff6a7,2026-03-07,71',Substitution,"Substitution: A. Ojeda out, M. Carrizo in",A. Ojeda,M. Carrizo
...,...,...,...,...,...,...,...
1781,7631e105,2026-02-22,13',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN
1782,7631e105,2026-02-22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN
1783,7631e105,2026-02-22,8',Substitution,"Substitution: J. Morris out, P. Rothrock in",J. Morris,P. Rothrock
1784,7631e105,2026-02-22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN
1785,7631e105,2026-02-22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN

In [273]:
### add feed_id per match 
df['feed_id'] = df.groupby('match_id').cumcount() + 1

In [274]:
df

,match_id,date,minute,title,comment,out_player,in_player,feed_id
2,6afff6a7,2026-03-07,87',Substitution,"Substitution: N. Fernández out, S. Reid in",N. Fernández,S. Reid,1
3,6afff6a7,2026-03-07,79',Attempt Saved,Attempt blocked. Máximo Carrizo's (New York Ci...,NaN,NaN,2
4,6afff6a7,2026-03-07,78',Substitution,"Substitution: M. Pašalić out, Tiago in",M. Pašalić,Tiago,3
5,6afff6a7,2026-03-07,71',Substitution,"Substitution: K. Parks out, R. Gustavo in",K. Parks,R. Gustavo,4
6,6afff6a7,2026-03-07,71',Substitution,"Substitution: A. Ojeda out, M. Carrizo in",A. Ojeda,M. Carrizo,5
...,...,...,...,...,...,...,...,...
1781,7631e105,2026-02-22,13',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN,34
1782,7631e105,2026-02-22,10',Attempt Saved,Attempt blocked. Cristian Roldan's (Seattle So...,NaN,NaN,35
1783,7631e105,2026-02-22,8',Substitution,"Substitution: J. Morris out, P. Rothrock in",J. Morris,P. Rothrock,36
1784,7631e105,2026-02-22,3',Attempt Saved,Attempt blocked. Nouhou Tolo's (Seattle Sounde...,NaN,NaN,37
1785,7631e105,2026-02-22,1',Attempt Saved,Attempt blocked. Albert Rusnák's (Seattle Soun...,NaN,NaN,38

In [275]:
## sort by date desc

df = df.sort_values(by=['date', 'match_id', 'feed_id'], ascending=[False, True, False]).reset_index(drop=False)

In [276]:
df

,index,match_id,date,minute,title,comment,out_player,in_player,feed_id
0,561,bb7391b6,2026-03-08,15',Yellow Card,Ender Echenique (FC Cincinnati) is shown the y...,NaN,NaN,38
1,560,bb7391b6,2026-03-08,19',Attempt Saved,Attempt blocked. Dániel Sallói's (Toronto FC) ...,NaN,NaN,37
2,559,bb7391b6,2026-03-08,25',Yellow Card,Benjamín Kuscevic (Toronto FC) is shown the ye...,NaN,NaN,36
3,558,bb7391b6,2026-03-08,29',Attempt Saved,Attempt saved. Emilio Aristizábal's (Toronto F...,NaN,NaN,35
4,557,bb7391b6,2026-03-08,29',Attempt Missed,Attempt missed. Djordje Mihailovic's (Toronto ...,NaN,NaN,34
...,...,...,...,...,...,...,...,...,...
1562,1598,dee239a9,2026-02-21,84',Substitution,"Substitution: Antony out, J. Ortiz in",Antony,J. Ortiz,5
1563,1597,dee239a9,2026-02-21,86',Attempt Missed,Attempt missed. Andrés Herrera's (Columbus Cre...,NaN,NaN,4
1564,1596,dee239a9,2026-02-21,88',Attempt Saved,Attempt saved. Cole Bassett's (Portland Timber...,NaN,NaN,3
1565,1595,dee239a9,2026-02-21,88',GOAL,Goal! 3:2. Ariel Lassiter (Portland Timbers) s...,NaN,NaN,2
1566,1594,dee239a9,2026-02-21,90',Substitution,"Substitution: K. Velde out, I. Smith in",K. Velde,I. Smith,1

In [277]:
### remove in_player and out_player columns
df = df.drop(columns=['in_player', 'out_player', 'index'])

In [280]:
### reorder columns
df = df[['match_id', 'date', 'feed_id', 'minute', 'title', 'comment']]

In [281]:
df

,match_id,date,feed_id,minute,title,comment
0,bb7391b6,2026-03-08,38,15',Yellow Card,Ender Echenique (FC Cincinnati) is shown the y...
1,bb7391b6,2026-03-08,37,19',Attempt Saved,Attempt blocked. Dániel Sallói's (Toronto FC) ...
2,bb7391b6,2026-03-08,36,25',Yellow Card,Benjamín Kuscevic (Toronto FC) is shown the ye...
3,bb7391b6,2026-03-08,35,29',Attempt Saved,Attempt saved. Emilio Aristizábal's (Toronto F...
4,bb7391b6,2026-03-08,34,29',Attempt Missed,Attempt missed. Djordje Mihailovic's (Toronto ...
...,...,...,...,...,...,...
1562,dee239a9,2026-02-21,5,84',Substitution,"Substitution: Antony out, J. Ortiz in"
1563,dee239a9,2026-02-21,4,86',Attempt Missed,Attempt missed. Andrés Herrera's (Columbus Cre...
1564,dee239a9,2026-02-21,3,88',Attempt Saved,Attempt saved. Cole Bassett's (Portland Timber...
1565,dee239a9,2026-02-21,2,88',GOAL,Goal! 3:2. Ariel Lassiter (Portland Timbers) s...
1566,dee239a9,2026-02-21,1,90',Substitution,"Substitution: K. Velde out, I. Smith in"

In [31]:
### check for nan teams

df[df['home_team'].isna() | df['away_team'].isna()]

Empty DataFrame
Columns: [match_id, date, feed_id, minute, title, comment, home_team, away_team]
Index: []

In [32]:
df

,match_id,date,feed_id,minute,title,comment,home_team,away_team
0,04a4ef01,2025-10-18,36,90'+7,Attempt Missed,Attempt missed. Nicolás Romero's (Minnesota Un...,LA,MIN
1,04a4ef01,2025-10-18,35,90'+7,Foul,Edwin Cerrillo (LA Galaxy) is shown the second...,LA,MIN
2,04a4ef01,2025-10-18,34,90'+5,Corner,Goal! 2:1. Joaquín Pereyra (Minnesota United F...,LA,MIN
3,04a4ef01,2025-10-18,33,89',Substitution,"Substitution: J. Paintsil out, T. Lepley in",LA,MIN
4,04a4ef01,2025-10-18,32,83',Attempt Saved,Attempt blocked. Joaquín Pereyra's (Minnesota ...,LA,MIN
...,...,...,...,...,...,...,...,...
38652,1cfa7fdb,2024-02-21,5,23',Attempt Saved,Attempt saved. Diego Gómez's (Inter Miami CF) ...,MIA,RSL
38653,1cfa7fdb,2024-02-21,4,21',Attempt Saved,Attempt blocked. Lionel Messi's (Inter Miami C...,MIA,RSL
38654,1cfa7fdb,2024-02-21,3,20',Attempt Saved,Attempt saved. Luis Suárez's (Inter Miami CF) ...,MIA,RSL
38655,1cfa7fdb,2024-02-21,2,15',Foul,Pablo Ruiz (Real Salt Lake) is shown the yello...,MIA,RSL
38656,1cfa7fdb,2024-02-21,1,6',Attempt Missed,Attempt missed. Luis Suárez's (Inter Miami CF)...,MIA,RSL

In [284]:
df.to_csv(
    "../../data/interim/matches/feed/cleaned_mls_match_feeds3.csv",
    index=False)

In [ ]:
def clean_feed(df):
    df = df.copy()
    
    df['title'] = df.apply(lambda x: 'Corner' if pd.notna(x['comment']) and 'corner' in x['comment'].lower() else x['title'], axis=1)

    df['title'] = df.apply(lambda x: 'Foul' if pd.notna(x['comment']) and 'foul' in x['comment'].lower() else x['title'], axis=1)

    df['title'] = df.apply(lambda x: 'Offside' if pd.notna(x['comment']) and 'offside' in x['comment'].lower() else x['title'], axis=1)   
    
    df = df[~df['comment'].str.contains('Lineups', na=False)]

    df = df[~df['title'].str.contains('KICK OFF|HALF TIME|FULL TIME|END OF SECOND HALF', na=False)]
    
    df = df[df['minute'].notna()]
    
    df = df.iloc[::-1].reset_index(drop=True)
    
    df['title'] = df['title'].fillna('Substitution')

    df['comment'] = df.apply(lambda x: f"Substitution: {x['out_player']} out, {x['in_player']} in" if x['title'] == 'Substitution' else x['comment'], axis=1)
    
    df['feed_id'] = df.groupby('match_id').cumcount() + 1
    
    df['date'] = df['date'].astype(str)
    
    df['date'] = df['date'].str.replace(r"^[A-Za-z]+ ", "", regex=True)

    month_map = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12"
    }

    df['date'] = df['date'].apply(
        lambda x: re.sub(
            r"[A-Za-z]+",
            lambda m: month_map.get(m.group(0).lower(), m.group(0)),
            x
        )
    )

    df['date'] = df['date'].apply(
        lambda x: x + " 2025" if not re.search(r"\b\d{4}\b", x) else x
    )
    
    df['date'] = pd.to_datetime(df['date'], format="%m %d %Y")
    
    df = df.drop(columns=['in_player', 'out_player'])

    df = df[['match_id', 'date', 'feed_id', 'minute', 'title', 'comment']]
    
    return df

In [ ]:
for file in glob.glob('G:/My Drive/GitHubProjects/MLS/data_files/scraped_raw/matches/feed/mls_match_feeds.csv'):
    df = pd.read_csv(file)
    cleaned_df = clean_feed(df)
    cleaned_df.to_csv(
        f"G:/My Drive/GitHubProjects/MLS/data_files/cleaned/matches/feed/cleaned_mls_match_feeds.csv",
        index=False)