In [64]:
import pandas as pd
import glob
import os
import re

In [65]:
files = glob.glob("../../data/raw/matches/players/*.csv")

In [74]:
import pandas as pd
import os
import re
from datetime import datetime

this_year = datetime.now().year
last_year = this_year - 1

dfs26 = []
dfs25 = []

pattern = re.compile(r"player_stats_.*\.csv")

for file in files:
    if pattern.search(file):
        mod_time = datetime.fromtimestamp(os.path.getmtime(file)).year
        
        try:
            if mod_time == this_year:
                dfs26.append(pd.read_csv(file, dtype={'match_id': str}))
            elif mod_time == last_year:
                dfs25.append(pd.read_csv(file, dtype={'match_id': str}))
        except Exception as e:
            print(f"Error reading {file}: {e}")

# Safety check before concat
df26 = pd.concat(dfs26, ignore_index=True) if dfs26 else pd.DataFrame()
df25 = pd.concat(dfs25, ignore_index=True) if dfs25 else pd.DataFrame()

print(f"2026: {len(df26)} rows across {len(dfs26)} files")
print(f"2025: {len(df25)} rows across {len(dfs25)} files")

2026: 1749 rows across 44 files
2025: 39674 rows across 1002 files

In [75]:
month_map = {
    "january": "01", "february": "02", "march": "03", "april": "04",
    "may": "05", "june": "06", "july": "07", "august": "08",
    "september": "09", "october": "10", "november": "11", "december": "12"
}

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# Step 1: Isolate first line immediately (handles \n, \r\n, \r)
df26['date'] = df26['date'].apply(lambda x: x.splitlines()[0].strip())

# Step 2: Remove day names
df26['date'] = df26['date'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in days])
).str.strip()

# Step 3: Lowercase
df26['date'] = df26['date'].str.lower()

# Step 4: Replace month name with number
df26['date'] = df26['date'].apply(
    lambda x: re.sub(
        r"([A-Za-z]+)",
        lambda m: month_map[m.group(1).lower()],
        x
    )
)

# Step 5: Append year if missing
df26['date'] = df26['date'].apply(
    lambda x: x + " 2026" if re.search(r"\d{4}$", x) is None else x
)

df26['date'] = pd.to_datetime(df26['date'], format="%m %d %Y")

df26

,Unnamed: 0,Player,Mins,G,xG,Conv%,SOT,Pass%,A,P,...,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC,match_id
0,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
1,T. Martins,71,0,0.00,0.0,0.0,93.9,0,92,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
2,T. Gray,90,0,0.02,1.0,0.0,89.4,1,76,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
3,M. Moralez,62,1,1.39,3.0,1.0,84.1,2,37,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
4,K. Parks,71,2,0.77,3.0,2.0,80.0,0,16,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,14,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1745,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,98,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1746,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,36,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1747,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,0,0,...,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0,7631e105
1748,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,0,0,...,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0,7631e105

In [76]:

# Step 1: Isolate first line immediately (handles \n, \r\n, \r)
df25['date'] = df25['date'].apply(lambda x: x.splitlines()[0].strip())

# Step 2: Remove day names
df25['date'] = df25['date'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in days])
).str.strip()

# Step 3: Lowercase
df25['date'] = df25['date'].str.lower()

# Step 4: Replace month name with number
df25['date'] = df25['date'].apply(
    lambda x: re.sub(
        r"([A-Za-z]+)",
        lambda m: month_map[m.group(1).lower()],
        x
    )
)

# Step 5: Append year if missing
df25['date'] = df25['date'].apply(
    lambda x: x + " 2025" if re.search(r"\d{4}$", x) is None else x
)

df25['date'] = pd.to_datetime(df25['date'], format="%m %d %Y")

df25

,Unnamed: 0,Player,Mins,G,xG,Conv%,SOT,Pass%,A,P,...,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC,match_id
0,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
1,T. Martins,90,0,0.00,0.0,0.0,84.1,0,58,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
2,T. Gray,90,0,0.00,0.0,0.0,77.6,0,52,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
3,M. Moralez,90,0,0.00,0.0,0.0,83.1,0,54,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
4,K. Parks,26,0,0.00,0.0,0.0,80.0,0,12,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39669,I. Toklomati,66,1,0.56,3.0,1.0,91.7,0,11,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0a5fe62f
39670,W. Zaha,78,0,0.12,3.0,1.0,80.7,1,25,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0a5fe62f
39671,S. Doumbia,88,0,0.00,0.0,0.0,85.2,1,23,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0a5fe62f
39672,J. Pulskamp,90,4,0.00,NaN,NaN,NaN,0,0,0,...,1.0,0.0,23.0,82.1,2.0,0.0,0.0,0.0,1.0,0a5fe62f
39673,K. Kahlina,90,2,0.00,NaN,NaN,NaN,0,0,0,...,2.0,0.0,26.0,86.7,6.0,0.0,0.0,0.0,0.0,0a5fe62f

In [79]:
precleandf = pd.concat([df25, df26], ignore_index=True)

In [82]:
precleandf

,Unnamed: 0,Player,Mins,G,xG,Conv%,SOT,Pass%,A,P,...,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC,match_id
0,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
1,T. Martins,90,0,0.00,0.0,0.0,84.1,0,58,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
2,T. Gray,90,0,0.00,0.0,0.0,77.6,0,52,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
3,M. Moralez,90,0,0.00,0.0,0.0,83.1,0,54,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
4,K. Parks,26,0,0.00,0.0,0.0,80.0,0,12,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919a513b
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41418,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,14,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
41419,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,98,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
41420,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,36,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
41421,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,0,0,...,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0,7631e105
41422,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,0,0,...,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0,7631e105

In [83]:
### rename columns shifted by one to the right
df = precleandf.rename(columns={
    'Unnamed: 0': 'Player',
    'Player': 'Mins',
    'Mins': 'G',
    'G': 'xG',
    'xG': 'Conv%',
    'Conv%': 'SOT',
    'SOT': 'Pass%',
    'Pass%': 'A',
    'A': 'P',
    'P': 'Cross',
    'Cross': 'CK',
    'CK': 'KP',
    'KP': 'AD',
    'AD': 'AD%',
    'AD%': 'FC',
    'FC': 'FS',
    'FS': 'OFF',
    'OFF': 'YC',
    'YC': 'RC1'
})

## remove second RC column
df = df.drop(columns=['RC'])

## rename rc1 to RC
df = df.rename(columns={'RC1': 'RC'})

In [ ]:
### grab date, match_id and each club name PER club id

matches = df[['match_id', 'date', 'club', 'side']].drop_duplicates()

matches

       match_id       date club  side
0      919a513b 2025-05-04  NYC  home
18     919a513b 2025-05-04  CIN  away
39     4cb316bb 2025-05-10  NSH  home
58     4cb316bb 2025-05-10  CLT  away
79     54fc52e2 2024-07-17  NSH  home
...         ...        ...  ...   ...
41324  3f3f51ea 2026-02-21  SKC  away
41344  5c78a593 2026-02-22   LA  home
41362  5c78a593 2026-02-22  NYC  away
41383  7631e105 2026-02-22  SEA  home
41402  7631e105 2026-02-22  COL  away

[2092 rows x 4 columns]

In [ ]:
### create separate columns for home and away clubs

matches['home_club'] = matches.apply(lambda x: x['club'] if x['side'] == 'home' else None, axis=1)
matches['away_club'] = matches.apply(lambda x: x['club'] if x['side'] == 'away' else None, axis=1)

matches = matches.groupby(['match_id', 'date']).agg({'home_club': 'first', 'away_club': 'first'}).reset_index()

matches

      match_id       date home_club away_club
0     00093bf5 2025-08-16       CHI       STL
1     006b3126 2025-10-11       MIA       ATL
2     00ba135d 2024-05-04       MIA      RBNY
3     00cdab1a 2025-06-14       RSL        DC
4     0182f52b 2025-07-19       MTL       CHI
...        ...        ...       ...       ...
1041  ff30d11e 2024-03-09       RSL       COL
1042  ff46f6c3 2024-06-22        DC       HOU
1043  ff4ea1b4 2025-05-17       COL       RSL
1044  ffb5ce29 2024-07-13       MTL       ATL
1045  ffcd9c5d 2024-03-30       ATX       DAL

[1046 rows x 4 columns]

In [ ]:
month_map = {
    "january": "01", "february": "02", "march": "03", "april": "04",
    "may": "05", "june": "06", "july": "07", "august": "08",
    "september": "09", "october": "10", "november": "11", "december": "12"
}

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# Step 1: Isolate first line immediately (handles \n, \r\n, \r)
matches['date'] = matches['date'].apply(lambda x: x.splitlines()[0].strip())

# Step 2: Remove day names
matches['date'] = matches['date'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in days])
).str.strip()

# Step 3: Lowercase
matches['date'] = matches['date'].str.lower()

# Step 4: Replace month name with number
matches['date'] = matches['date'].apply(
    lambda x: re.sub(
        r"([A-Za-z]+)",
        lambda m: month_map[m.group(1).lower()],
        x
    )
)

# Step 5: Append year if missing
matches['date'] = matches['date'].apply(
    lambda x: x + " 2026" if re.search(r"\d{4}$", x) is None else x
)

matches['date'] = pd.to_datetime(matches['date'], format="%m %d %Y")

matches

      match_id       date home_club away_club
0     00093bf5 2026-08-16       CHI       STL
1     006b3126 2026-10-11       MIA       ATL
2     00ba135d 2024-05-04       MIA      RBNY
3     00cdab1a 2026-06-14       RSL        DC
4     0182f52b 2026-07-19       MTL       CHI
...        ...        ...       ...       ...
1041  ff30d11e 2024-03-09       RSL       COL
1042  ff46f6c3 2024-06-22        DC       HOU
1043  ff4ea1b4 2026-05-17       COL       RSL
1044  ffb5ce29 2024-07-13       MTL       ATL
1045  ffcd9c5d 2024-03-30       ATX       DAL

[1046 rows x 4 columns]

In [ ]:
### rename home club and away to team

matches = matches.rename(columns={'home_club': 'home_team', 'away_club': 'away_team'})

matches

      match_id       date home_team away_team
0     00093bf5 2025-08-16       CHI       STL
1     006b3126 2025-10-11       MIA       ATL
2     00ba135d 2024-05-04       MIA      RBNY
3     00cdab1a 2025-06-14       RSL        DC
4     0182f52b 2025-07-19       MTL       CHI
...        ...        ...       ...       ...
1041  ff30d11e 2024-03-09       RSL       COL
1042  ff46f6c3 2024-06-22        DC       HOU
1043  ff4ea1b4 2025-05-17       COL       RSL
1044  ffb5ce29 2024-07-13       MTL       ATL
1045  ffcd9c5d 2024-03-30       ATX       DAL

[1046 rows x 4 columns]

In [ ]:
matches_scores = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/matches_past_cleaned_0326.csv')
matches_scores2 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/cleaned_mls_matches_master.csv')

matches_scores = pd.concat([matches_scores, matches_scores2], ignore_index=True)

matches_scores['date'] = pd.to_datetime(matches_scores['date'], format="%Y-%m-%d")

In [ ]:
matches_scores

           date home_team away_team  home_score  away_score  match_id
0    2026-03-07       NYC       ORL           5           0  8865ae2a
1    2026-03-07        DC       MIA           1           2  0c956f37
2    2026-03-07       ATL       RSL           2           3  b0713dc5
3    2026-03-07       CLT       ATX           3           1  646c3889
4    2026-03-07       CLB       CHI           0           0  5291010f
...         ...       ...       ...         ...         ...       ...
1501 2023-02-25       PHI       CLB           4           1  a2b8daa3
1502 2023-02-25       ATX       STL           2           3  e5ef0678
1503 2023-02-25       DAL       MIN           0           1  fbd05677
1504 2023-02-25       VAN       RSL           1           2  e74b26e8
1505 2023-02-26       SEA       COL           4           0  181569f7

[1506 rows x 6 columns]

In [ ]:
matches['away_team'] = matches['away_team'].str.lower()
matches['home_team'] = matches['home_team'].str.lower()

matches_scores['away_team'] = matches_scores['away_team'].str.lower()
matches_scores['home_team'] = matches_scores['home_team'].str.lower()

In [ ]:
#### replace match id in matches scores with match id in matches according to date and teams

matches_scores2 = matches.merge(matches_scores, on=['date', 'home_team', 'away_team'], how='left')

matches_scores2

,match_id_x,date,home_team,away_team,home_score,away_score,match_id_y
0,00093bf5,2025-08-16,chi,stl,3.0,2.0,16760364
1,006b3126,2025-10-11,mia,atl,4.0,0.0,7f9d56d1
2,00ba135d,2024-05-04,mia,rbny,6.0,2.0,03ff876f
3,00cdab1a,2025-06-14,rsl,dc,2.0,0.0,3be6fca2
4,0182f52b,2025-07-19,mtl,chi,0.0,2.0,f3ec60a0
...,...,...,...,...,...,...,...
1041,ff30d11e,2024-03-09,rsl,col,1.0,2.0,0fde95fc
1042,ff46f6c3,2024-06-22,dc,hou,1.0,4.0,b8062fc1
1043,ff4ea1b4,2025-05-17,col,rsl,1.0,0.0,ddd3b473
1044,ffb5ce29,2024-07-13,mtl,atl,1.0,0.0,75f5e215
1045,ffcd9c5d,2024-03-30,atx,dal,2.0,1.0,6df8e7ef

In [ ]:
###  keep y only and rename to match_id

matches_scores = matches_scores.drop(columns=['match_id_y'])

matches_scores = matches_scores.rename(columns={'match_id_x': 'match_id'})

matches_scores

KeyError: "['match_id_y'] not found in axis"

In [ ]:
matches_scores.to_csv("../../data/interim/matches/clean_matches_0326.csv", index=False)

In [18]:
df

,Player,Mins,G,xG,Conv%,SOT,Pass%,A,P,Cross,...,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC,match_id
0,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
1,T. Martins,71,0,0.00,0.0,0.0,93.9,0,92,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
2,T. Gray,90,0,0.02,1.0,0.0,89.4,1,76,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
3,M. Moralez,62,1,1.39,3.0,1.0,84.1,2,37,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
4,K. Parks,71,2,0.77,3.0,2.0,80.0,0,16,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6afff6a7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,14,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1745,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,98,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1746,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,36,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7631e105
1747,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,0,0,...,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0,7631e105
1748,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,0,0,...,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0,7631e105

In [84]:
## rename columns
df = df.rename(columns={
    'Player': 'player_name',
    'Mins': 'minutes',
    'G' : 'goals',
    'xG': 'expected_goals',
    'Conv%' : 'shot_conv_perc',
    'SOT' : 'on_target',
    'Pass%' : 'pass_perc',
    'A' : 'assists',
    'P' : 'passes',
    'Cross' : 'cross',
    'CK' : 'corner_kick',
    'KP' : 'key_pass',
    'AD' : 'aerial',
    'AD%' : 'aerial_perc',
    'FC' : 'fouls',
    'FS' : 'fouls_against',
    'OFF' : 'offside',
    'YC' : 'yellow_card',
    'RC' : 'red_card',
    'GS': 'goals_saved',
    'GA': 'goals_against',
    'XGA': 'expected_goals_against',
    'Pass`': 'passes_completed',
    'THRW': 'gk_throws',
    'LB': 'gk_long_balls',
    'LNCH': 'gk_launches',
    'GKSV': 'goals_on_kick',
    'CC': 'corners_conceded'
})

In [85]:
## move match_id to the front

df = df[['match_id'] + ['date'] + [col for col in df.columns if col not in ['match_id', 'date']]]

In [22]:
month_map = {
        "january": "01", "february": "02", "march": "03", "april": "04",
        "may": "05", "june": "06", "july": "07", "august": "08",
        "september": "09", "october": "10", "november": "11", "december": "12"
    }

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

df['date'] = df['date'].apply(lambda x: ' '.join([word for word in x.split() if word not in days]))

df['date'] = df['date'].str.split('\n').str[0]

df['date'] = df['date'].apply(
        lambda x: re.sub(
            r"([A-Za-z]+)",
            lambda m: month_map[m.group(1).lower()],
            x
        )
    )

df['date'] = df['date'].apply(lambda x: x + " 2026" if re.search(r"\d{4}$", x) is None else x)

df['date'] = pd.to_datetime(df['date'], format="%m %d %Y")

In [86]:
df

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,club,goals_saved,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded
0,919a513b,2025-05-04,T. Romero,0,0,0.00,0.0,0.0,0.0,0,...,NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,919a513b,2025-05-04,T. Martins,90,0,0.00,0.0,0.0,84.1,0,...,NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,919a513b,2025-05-04,T. Gray,90,0,0.00,0.0,0.0,77.6,0,...,NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,919a513b,2025-05-04,M. Moralez,90,0,0.00,0.0,0.0,83.1,0,...,NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,919a513b,2025-05-04,K. Parks,26,0,0.00,0.0,0.0,80.0,0,...,NYC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41418,7631e105,2026-02-22,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,...,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41419,7631e105,2026-02-22,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,...,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41420,7631e105,2026-02-22,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,...,COL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41421,7631e105,2026-02-22,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,...,SEA,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0
41422,7631e105,2026-02-22,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,...,COL,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0

In [87]:
### order by date then match id desc

df = df.sort_values(by=['date', 'match_id'], ascending=[False, False])

In [88]:
### rename clubs according to dictionaries 

clubs = [
    "Atlanta United",
    "Austin FC",
    "CF Montréal",
    "Charlotte FC",
    "Chicago Fire FC",
    "FC Cincinnati",
    "Colorado Rapids",
    "Columbus Crew",
    "D.C. United",
    "FC Dallas",
    "Houston Dynamo FC",
    "Sporting Kansas City",
    "LA Galaxy",
    "Los Angeles Football Club",
    "Inter Miami CF",
    "Minnesota United FC",
    "Minnesota United",
    "Nashville SC",
    "New England Revolution",
    "New York City Football Club",
    "New York City FC",
    "New York Red Bulls",
    "Orlando City",
    "Philadelphia Union",
    "Portland Timbers",
    "Real Salt Lake",
    "San Diego FC",
    "San Jose Earthquakes",
    "Seattle Sounders FC",
    "St. Louis CITY SC",
    "Toronto FC",
    "Vancouver Whitecaps FC"
]

team_map = {
    "Atlanta United": "ATL",
    "Austin FC": "ATX",
    "CF Montréal": "MTL",
    "Charlotte FC": "CLT",
    "Chicago Fire FC": "CHI",
    "FC Cincinnati": "CIN",
    "Colorado Rapids": "COL",
    "Columbus Crew": "CLB",
    "D.C. United": "DC",
    "FC Dallas": "DAL",
    "Houston Dynamo FC": "HOU",
    "Sporting Kansas City": "SKC",
    "LA Galaxy": "LA",
    "Los Angeles Football Club": "LAFC",
    "Inter Miami CF": "MIA",
    "Minnesota United": "MIN",
    "Minnesota United FC": "MIN",
    "Nashville SC": "NSH",
    "New England Revolution": "NE",
    "New York City Football Club": "NYC",
    "New York City FC": "NYC",
    "New York Red Bulls": "RBNY",
    "Orlando City": "ORL",
    "Philadelphia Union": "PHI",
    "Portland Timbers": "POR",
    "Real Salt Lake": "RSL",
    "San Diego FC": "SD",
    "San Jose Earthquakes": "SJ",
    "Seattle Sounders FC": "SEA",
    "St. Louis CITY SC": "STL",
    "Toronto FC": "TOR",
    "Vancouver Whitecaps FC": "VAN"
}

In [89]:
def norm_team(s):
    if pd.isna(s):
        return ""
    return (
        str(s).lower()
        .strip()
        .replace(".", "")
        .replace("’", "'")
    )

# 1) Build a normalized map from your official team_map
team_map_norm = {norm_team(k): v for k, v in team_map.items()}

# 2) Add aliases that appear in your current data
aliases = {
    "chicago fire": "CHI",                 # vs Chicago Fire FC
    "houston dynamo": "HOU",               # vs Houston Dynamo FC
    "dc united": "DC",                     # vs D.C. United
    "los angeles fc": "LAFC",              # vs Los Angeles Football Club
    "orlando city sc": "ORL",              # vs Orlando City
    "st louis city sc": "STL",             # vs St. Louis CITY SC
    "inter miami": "MIA",                  # vs Inter Miami CF
    "minnesota united fc": "MIN",          # already there but keep explicit
}
abbrs = set(team_map_norm.values())

df["club_norm"] = df["club"].apply(norm_team)

df["club_abbr"] = df["club_norm"].apply(
    lambda x: x.upper() if x.upper() in abbrs else team_map_norm.get(x)
)

In [90]:
df["club_abbr"].isna().sum()

24

In [91]:
### show nan in club_abbr

df[df["club_abbr"].isna()]

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club_norm,club_abbr
28479,026a346e,2024-04-30,D. Lowe,6,0,0.00,0.0,0.0,50.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28480,026a346e,2024-04-30,M. Real,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28481,026a346e,2024-04-30,J. Elliott,90,0,0.26,2.0,0.0,80.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28482,026a346e,2024-04-30,J. Glesnes,90,0,0.00,0.0,0.0,71.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28483,026a346e,2024-04-30,O. Mbaizo,45,0,0.00,0.0,0.0,88.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28484,026a346e,2024-04-30,N. Harriel,90,0,0.15,1.0,1.0,84.1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28485,026a346e,2024-04-30,K. Wagner,45,0,0.11,1.0,0.0,70.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28486,026a346e,2024-04-30,J. Rafanello,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28487,026a346e,2024-04-30,D. Gazdag,90,1,0.73,2.0,2.0,86.1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28488,026a346e,2024-04-30,J. Martínez,45,0,0.05,2.0,0.0,64.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28489,026a346e,2024-04-30,A. Bedoya,45,0,0.00,0.0,0.0,85.2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28490,026a346e,2024-04-30,J. McGlynn,45,1,0.02,1.0,1.0,83.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28491,026a346e,2024-04-30,J. Bueno,45,0,0.06,1.0,0.0,85.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28492,026a346e,2024-04-30,L. Flach,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28493,026a346e,2024-04-30,Q. Sullivan,90,0,0.02,1.0,0.0,65.7,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28494,026a346e,2024-04-30,M. Uhre,81,0,0.00,0.0,0.0,66.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28495,026a346e,2024-04-30,J. Carranza,84,0,0.42,4.0,2.0,78.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28496,026a346e,2024-04-30,C. Donovan,9,0,0.03,1.0,1.0,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28497,026a346e,2024-04-30,A. Rick,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28498,026a346e,2024-04-30,T. Baribo,6,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28499,026a346e,2024-04-30,S. Ngabo,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28500,026a346e,2024-04-30,M. Anderson,6,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28521,026a346e,2024-04-30,A. Blake,6,0,0.00,NaN,NaN,NaN,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,None
28522,026a346e,2024-04-30,O. Semmle,90,2,0.00,NaN,NaN,NaN,0,...,0.0,15.0,75.0,6.0,0.0,0.0,0.0,0.0,,None

In [ ]:
### find all rows from 4/30/24

df_4_30_24 = df[df['date'] == '4/30/24'] 

df_4_30_24

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club_norm,club_abbr
28479,026a346e,2024-04-30,D. Lowe,6,0,0.00,0.0,0.0,50.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28480,026a346e,2024-04-30,M. Real,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28481,026a346e,2024-04-30,J. Elliott,90,0,0.26,2.0,0.0,80.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28482,026a346e,2024-04-30,J. Glesnes,90,0,0.00,0.0,0.0,71.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28483,026a346e,2024-04-30,O. Mbaizo,45,0,0.00,0.0,0.0,88.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28484,026a346e,2024-04-30,N. Harriel,90,0,0.15,1.0,1.0,84.1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28485,026a346e,2024-04-30,K. Wagner,45,0,0.11,1.0,0.0,70.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28486,026a346e,2024-04-30,J. Rafanello,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28487,026a346e,2024-04-30,D. Gazdag,90,1,0.73,2.0,2.0,86.1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28488,026a346e,2024-04-30,J. Martínez,45,0,0.05,2.0,0.0,64.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28489,026a346e,2024-04-30,A. Bedoya,45,0,0.00,0.0,0.0,85.2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28490,026a346e,2024-04-30,J. McGlynn,45,1,0.02,1.0,1.0,83.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28491,026a346e,2024-04-30,J. Bueno,45,0,0.06,1.0,0.0,85.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28492,026a346e,2024-04-30,L. Flach,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28493,026a346e,2024-04-30,Q. Sullivan,90,0,0.02,1.0,0.0,65.7,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28494,026a346e,2024-04-30,M. Uhre,81,0,0.00,0.0,0.0,66.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28495,026a346e,2024-04-30,J. Carranza,84,0,0.42,4.0,2.0,78.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28496,026a346e,2024-04-30,C. Donovan,9,0,0.03,1.0,1.0,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28497,026a346e,2024-04-30,A. Rick,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28498,026a346e,2024-04-30,T. Baribo,6,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28499,026a346e,2024-04-30,S. Ngabo,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28500,026a346e,2024-04-30,M. Anderson,6,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,None
28501,026a346e,2024-04-30,J. Bell,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28502,026a346e,2024-04-30,D. Musovski,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28503,026a346e,2024-04-30,X. Arreaga,0,0,0.00,0.0,0.0,100.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28504,026a346e,2024-04-30,N. Tolo,90,0,0.00,0.0,0.0,72.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28505,026a346e,2024-04-30,J. Ragen,90,0,0.08,1.0,1.0,54.5,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28506,026a346e,2024-04-30,Y. Gómez,90,0,0.00,0.0,0.0,52.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28507,026a346e,2024-04-30,J. Mior,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28508,026a346e,2024-04-30,C. Roldan,90,0,0.34,2.0,0.0,90.2,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28509,026a346e,2024-04-30,A. Rusnák,31,0,0.00,0.0,0.0,81.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28510,026a346e,2024-04-30,A. Roldan,90,0,0.08,1.0,0.0,75.6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28511,026a346e,2024-04-30,L. Chú,59,0,0.00,0.0,0.0,78.6,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28512,026a346e,2024-04-30,O. Vargas,90,1,0.02,1.0,1.0,86.4,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28513,026a346e,2024-04-30,D. Leyva,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28514,026a346e,2024-04-30,J. Atencio,90,0,0.05,1.0,0.0,83.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28515,026a346e,2024-04-30,R. Ruidíaz,84,2,1.22,6.0,3.0,76.9,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28516,026a346e,2024-04-30,J. Morris,89,0,0.41,3.0,0.0,78.6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28517,026a346e,2024-04-30,D. Teves,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28518,026a346e,2024-04-30,P. Rothrock,1,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28519,026a346e,2024-04-30,C. Baker,6,0,0.00,0.0,0.0,50.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28520,026a346e,2024-04-30,J. Castro,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sea,SEA
28521,026a346e,2024-04-30,A. Blake,6,0,0.00,NaN,NaN,NaN,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,None
28522,026a346e,2024-04-30,O. Semmle,90,2,0.00,NaN,NaN,NaN,0,...,0.0,15.0,75.0,6.0,0.0,0.0,0.0,0.0,,None
28523,026a346e,2024-04-30,A. Thomas,90,5,0.00,NaN,NaN,NaN,0,...,0.0,5.0,25.0,8.0,0.0,0.0,0.0,0.0,sea,SEA

In [93]:
### replace nan club with 'PHI' 

df['club_abbr'] = df['club_abbr'].fillna('PHI')

### print unique club_abbr values

df["club_abbr"].unique()

array(['RBNY', 'MTL', 'CIN', 'TOR', 'PHI', 'SJ', 'POR', 'VAN', 'NSH',
       'MIN', 'STL', 'SEA', 'COL', 'LA', 'CLT', 'ATX', 'DC', 'MIA', 'SKC',
       'SD', 'NYC', 'ORL', 'ATL', 'RSL', 'LAFC', 'DAL', 'CLB', 'CHI',
       'HOU', 'NE'], dtype=object)

In [94]:
### remove club_norm column

df = df.drop(columns=['club_norm', 'club'])

#### renaame club_abbr to club

df = df.rename(columns={'club_abbr': 'club'})

In [95]:
df

,match_id,date,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,goals_saved,goals_against,expected_goals_against,Pass,gk_throws,gk_long_balls,gk_launches,GK,corners_conceded,club
40152,c1d67317,2026-03-08,T. Parker,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RBNY
40153,c1d67317,2026-03-08,J. McCarthy,0,0,0.00,0.0,0.0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RBNY
40154,c1d67317,2026-03-08,C. Cowell,85,0,0.06,1.0,1.0,65.7,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RBNY
40155,c1d67317,2026-03-08,R. Voloder,90,0,0.04,1.0,0.0,92.1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RBNY
40156,c1d67317,2026-03-08,J. Marshall-Rutty,77,0,0.02,1.0,0.0,94.6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RBNY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13108,1cfa7fdb,2024-02-21,F. Barajas,24,0,0.00,0.0,0.0,81.8,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RSL
13109,1cfa7fdb,2024-02-21,E. Eneli,90,0,0.00,0.0,0.0,93.3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RSL
13110,1cfa7fdb,2024-02-21,N. Palacio,66,0,0.02,1.0,0.0,92.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RSL
13111,1cfa7fdb,2024-02-21,D. Callender,90,2,0.00,NaN,NaN,NaN,0,...,0.0,0.0,26.0,83.9,4.0,0.0,0.0,0.0,0.0,MIA
13112,1cfa7fdb,2024-02-21,Z. MacMath,90,6,0.00,NaN,NaN,NaN,0,...,2.0,0.0,25.0,75.8,9.0,0.0,0.0,0.0,0.0,RSL

In [97]:
### how many unique match ids

df['match_id'].nunique()

1046

In [96]:
df.to_csv(
    f"../../data/interim/matches/players/cleaned_mls_match_player_stats031926.csv",
    index=False)

In [71]:
def clean_players(df):
    df = df.rename(columns={
        'Player': 'player_name',
        'Mins': 'minutes',
        'G' : 'goals',
        'xG': 'expected_goals',
        'Conv%' : 'shot_conv_perc',
        'SOT' : 'on_target',
        'Pass%' : 'pass_perc',
        'A' : 'assists',
        'P' : 'passes',
        'Cross' : 'cross',
        'CK' : 'corner_kick',
        'KP' : 'key_pass',
        'AD' : 'aerial',
        'AD%' : 'aerial_perc',
        'FC' : 'fouls',
        'FS' : 'fouls_against',
        'OFF' : 'offside',
        'YC' : 'yellow_card',
        'RC' : 'red_card'
    })
    
    df = df[['match_id'] + [col for col in df.columns if col != 'match_id']]
    
    return df

In [ ]:
df = []

for file in glob.glob('G:/My Drive/GitHubProjects/MLS/data/raw/matches/players/player_stats_*.csv'):
    read = pd.read_csv(file)
    cleaned_df = clean_players(read)
    filename = os.path.basename(file)
    df.append(cleaned_df)
    
    
    
df = pd.concat(df, ignore_index=True)

,match_id,Unnamed: 0,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,date,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC
0,919a513b,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,...,Sunday May 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,919a513b,T. Martins,90,0,0.00,0.0,0.0,84.1,0,58,...,Sunday May 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,919a513b,T. Gray,90,0,0.00,0.0,0.0,77.6,0,52,...,Sunday May 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,919a513b,M. Moralez,90,0,0.00,0.0,0.0,83.1,0,54,...,Sunday May 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,919a513b,K. Parks,26,0,0.00,0.0,0.0,80.0,0,12,...,Sunday May 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41418,7630999999999999289751995875466473865476733141...,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,14,...,Sunday February 22\nLumen Field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41419,7630999999999999289751995875466473865476733141...,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,98,...,Sunday February 22\nLumen Field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41420,7630999999999999289751995875466473865476733141...,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,36,...,Sunday February 22\nLumen Field,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41421,7630999999999999289751995875466473865476733141...,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,0,...,Sunday February 22\nLumen Field,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0
41422,7630999999999999289751995875466473865476733141...,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,0,...,Sunday February 22\nLumen Field,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0

In [78]:
clean_df = clean_players(df)

clean_df

,match_id,Unnamed: 0,player_name,minutes,goals,expected_goals,shot_conv_perc,on_target,pass_perc,assists,...,date,GS,GA,XGA,Pass,THRW,LB,LNCH,GK,CC
0,919a513b,T. Romero,0,0,0.00,0.0,0.0,0.0,0,0,...,2025-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,919a513b,T. Martins,90,0,0.00,0.0,0.0,84.1,0,58,...,2025-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,919a513b,T. Gray,90,0,0.00,0.0,0.0,77.6,0,52,...,2025-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,919a513b,M. Moralez,90,0,0.00,0.0,0.0,83.1,0,54,...,2025-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,919a513b,K. Parks,26,0,0.00,0.0,0.0,80.0,0,12,...,2025-05-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41418,7631e105,A. Manyoma,22,0,0.02,1.0,0.0,82.3,0,14,...,2026-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41419,7631e105,L. Herrington,90,0,0.00,0.0,0.0,98.0,0,98,...,2026-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41420,7631e105,H. Ojediran,59,0,0.08,2.0,1.0,92.3,0,36,...,2026-02-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41421,7631e105,A. Thomas,90,3,0.00,NaN,NaN,NaN,0,0,...,2026-02-22,0.0,0.0,11.0,55.0,6.0,0.0,0.0,0.0,0.0
41422,7631e105,Z. Steffen,90,3,0.00,NaN,NaN,NaN,0,0,...,2026-02-22,2.0,0.0,32.0,80.0,8.0,0.0,0.0,0.0,0.0