In [18]:
import pandas as pd
from sqlalchemy import create_engine
import os
import glob

db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [21]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/teams/mls_match_team_stats_reframed_full_until0326.csv')

In [22]:
df

,match_id,general_aerial_duels_won_home,general_blocked_shots_home,general_blocked_home,general_clean_sheets_home,general_clearances_home,general_corners_home,general_expected_goals_home,general_fouls_home,general_goalkeeper_saves_home,...,possession_71_75_away,possession_76_80_away,possession_81_85_away,possession_86_90_away,shooting_blocked_away,shooting_goals_away,shooting_off_target_away,shooting_on_target_away,xg_shots_away,xg_total_team_xg_away
0,43ba7695,6.0,4.0,4.0,0.0,6.0,9.0,3.0,12.0,3.0,...,50.28,61.16,43.51,34.91,2.0,3.0,2.0,6.0,10.0,2.0
1,85bb856a,14.0,1.0,1.0,0.0,3.0,2.0,2.0,16.0,1.0,...,57.37,40.05,74.32,41.92,3.0,4.0,1.0,5.0,9.0,1.7
2,588d481f,8.0,4.0,4.0,0.0,3.0,4.0,1.4,6.0,3.0,...,47.48,35.72,16.70,55.20,1.0,1.0,3.0,4.0,8.0,0.4
3,1b458adf,8.0,9.0,9.0,0.0,8.0,3.0,1.1,10.0,2.0,...,33.44,42.86,23.66,32.48,3.0,3.0,2.0,5.0,11.0,1.5
4,5bce4433,10.0,2.0,2.0,0.0,5.0,2.0,1.3,12.0,4.0,...,41.31,45.27,33.57,42.54,3.0,0.0,1.0,4.0,9.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,dee239a9,6.0,1.0,1.0,0.0,16.0,6.0,1.3,5.0,3.0,...,51.39,40.69,78.63,34.66,6.0,2.0,5.0,5.0,16.0,1.1
1041,eaff4742,10.0,5.0,5.0,0.0,10.0,12.0,2.6,12.0,3.0,...,40.48,46.65,32.17,15.81,3.0,0.0,6.0,3.0,12.0,1.2
1042,f5d62f89,10.0,4.0,4.0,0.0,12.0,10.0,1.8,13.0,2.0,...,45.98,46.59,54.37,60.45,1.0,0.0,3.0,2.0,8.0,0.4
1043,fc3f246b,32.0,2.0,2.0,0.0,3.0,11.0,1.4,20.0,2.0,...,46.79,52.76,47.75,40.09,2.0,1.0,2.0,3.0,7.0,0.8
1044,ff05beda,9.0,2.0,2.0,0.0,13.0,2.0,0.9,16.0,4.0,...,40.41,70.19,82.50,34.93,5.0,4.0,2.0,8.0,16.0,1.2

In [ ]:
### check match on 03-01-25 
df[df["date"] == "2025-03-01"]

In [23]:
df = df.drop(columns=["general_open_play_cross_pct_home"])

In [24]:
df_cols = pd.DataFrame(df.columns)

df_cols

                                 0
0                         match_id
1    general_aerial_duels_won_home
2       general_blocked_shots_home
3             general_blocked_home
4        general_clean_sheets_home
..                             ...
109            shooting_goals_away
110       shooting_off_target_away
111        shooting_on_target_away
112                  xg_shots_away
113          xg_total_team_xg_away

[114 rows x 1 columns]

In [8]:
df.to_sql('matches', con=engine, if_exists='append', index=False)

44

In [1]:
df2 = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/teams/mls_match_team_stats_with_match_id.csv')
df2

NameError: name 'pd' is not defined

In [7]:
### remove date, home team, away team columns

df2 = df2.drop(columns=['date', 'home_team', 'away_team'])

In [44]:
df.dtypes

match_id                          object
general_aerial_duels_won_home    float64
general_blocked_shots_home       float64
general_blocked_home             float64
general_clean_sheets_home        float64
                                  ...
shooting_off_target_away         float64
shooting_on_target_away          float64
xg_shots_on_target_away          float64
xg_shots_away                    float64
xg_total_team_xg_away            float64
Length: 117, dtype: object

In [25]:
### remove general_blocked, general_goals, general_off_target and general_on_target columns for both home and away

df = df.drop(columns=['general_blocked_home', 'general_blocked_away',
                      'general_goals_home', 'general_goals_away',
                        'general_off_target_home', 'general_off_target_away',
                        'general_on_target_home', 'general_on_target_away'])

In [26]:
df = df.drop(columns=['xg_shots_on_goal_home', 'xg_shots_on_goal_away'])

KeyError: "['xg_shots_on_goal_home', 'xg_shots_on_goal_away'] not found in axis"

In [27]:
df

,match_id,general_aerial_duels_won_home,general_blocked_shots_home,general_clean_sheets_home,general_clearances_home,general_corners_home,general_expected_goals_home,general_fouls_home,general_goalkeeper_saves_home,general_goals_conceded_home,...,possession_71_75_away,possession_76_80_away,possession_81_85_away,possession_86_90_away,shooting_blocked_away,shooting_goals_away,shooting_off_target_away,shooting_on_target_away,xg_shots_away,xg_total_team_xg_away
0,43ba7695,6.0,4.0,0.0,6.0,9.0,3.0,12.0,3.0,3.0,...,50.28,61.16,43.51,34.91,2.0,3.0,2.0,6.0,10.0,2.0
1,85bb856a,14.0,1.0,0.0,3.0,2.0,2.0,16.0,1.0,4.0,...,57.37,40.05,74.32,41.92,3.0,4.0,1.0,5.0,9.0,1.7
2,588d481f,8.0,4.0,0.0,3.0,4.0,1.4,6.0,3.0,1.0,...,47.48,35.72,16.70,55.20,1.0,1.0,3.0,4.0,8.0,0.4
3,1b458adf,8.0,9.0,0.0,8.0,3.0,1.1,10.0,2.0,3.0,...,33.44,42.86,23.66,32.48,3.0,3.0,2.0,5.0,11.0,1.5
4,5bce4433,10.0,2.0,0.0,5.0,2.0,1.3,12.0,4.0,0.0,...,41.31,45.27,33.57,42.54,3.0,0.0,1.0,4.0,9.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,dee239a9,6.0,1.0,0.0,16.0,6.0,1.3,5.0,3.0,2.0,...,51.39,40.69,78.63,34.66,6.0,2.0,5.0,5.0,16.0,1.1
1041,eaff4742,10.0,5.0,0.0,10.0,12.0,2.6,12.0,3.0,0.0,...,40.48,46.65,32.17,15.81,3.0,0.0,6.0,3.0,12.0,1.2
1042,f5d62f89,10.0,4.0,0.0,12.0,10.0,1.8,13.0,2.0,0.0,...,45.98,46.59,54.37,60.45,1.0,0.0,3.0,2.0,8.0,0.4
1043,fc3f246b,32.0,2.0,0.0,3.0,11.0,1.4,20.0,2.0,1.0,...,46.79,52.76,47.75,40.09,2.0,1.0,2.0,3.0,7.0,0.8
1044,ff05beda,9.0,2.0,0.0,13.0,2.0,0.9,16.0,4.0,4.0,...,40.41,70.19,82.50,34.93,5.0,4.0,2.0,8.0,16.0,1.2

In [28]:
columns = df.columns.tolist()

print(columns)

['match_id', 'general_aerial_duels_won_home', 'general_blocked_shots_home', 'general_clean_sheets_home', 'general_clearances_home', 'general_corners_home', 'general_expected_goals_home', 'general_fouls_home', 'general_goalkeeper_saves_home', 'general_goals_conceded_home', 'general_interceptions_home', 'general_offsides_home', 'general_open_play_pass_pct_home', 'general_overall_pct_home', 'general_passing_accuracy_pct_home', 'general_possession_pct_home', 'general_red_cards_home', 'general_set_piece_cross_pct_home', 'general_shots_against_home', 'general_shots_on_goal_home', 'general_shots_home', 'general_total_crosses_home', 'general_total_passes_home', 'general_xg_conceded_home', 'general_yellow_cards_home', 'passing_open_play_cross_pct_home', 'passing_open_play_pass_pct_home', 'passing_overall_pct_home', 'passing_set_piece_cross_pct_home', 'possession_0_5_home', 'possession_11_15_home', 'possession_16_20_home', 'possession_21_25_home', 'possession_26_30_home', 'possession_31_35_home', 'possession_36_40_home', 'possession_41_45_home', 'possession_46_50_home', 'possession_51_55_home', 'possession_56_60_home', 'possession_61_65_home', 'possession_66_70_home', 'possession_6_10_home', 'possession_71_75_home', 'possession_76_80_home', 'possession_81_85_home', 'possession_86_90_home', 'shooting_blocked_home', 'shooting_goals_home', 'shooting_off_target_home', 'shooting_on_target_home', 'xg_shots_home', 'xg_total_team_xg_home', 'general_aerial_duels_won_away', 'general_blocked_shots_away', 'general_clean_sheets_away', 'general_clearances_away', 'general_corners_away', 'general_expected_goals_away', 'general_fouls_away', 'general_goalkeeper_saves_away', 'general_goals_conceded_away', 'general_interceptions_away', 'general_offsides_away', 'general_open_play_cross_pct_away', 'general_open_play_pass_pct_away', 'general_overall_pct_away', 'general_passing_accuracy_pct_away', 'general_possession_pct_away', 'general_red_cards_away', 'general_set_piece_cross_pct_away', 'general_shots_against_away', 'general_shots_on_goal_away', 'general_shots_away', 'general_total_crosses_away', 'general_total_passes_away', 'general_xg_conceded_away', 'general_yellow_cards_away', 'passing_open_play_cross_pct_away', 'passing_open_play_pass_pct_away', 'passing_overall_pct_away', 'passing_set_piece_cross_pct_away', 'possession_0_5_away', 'possession_11_15_away', 'possession_16_20_away', 'possession_21_25_away', 'possession_26_30_away', 'possession_31_35_away', 'possession_36_40_away', 'possession_41_45_away', 'possession_46_50_away', 'possession_51_55_away', 'possession_56_60_away', 'possession_61_65_away', 'possession_66_70_away', 'possession_6_10_away', 'possession_71_75_away', 'possession_76_80_away', 'possession_81_85_away', 'possession_86_90_away', 'shooting_blocked_away', 'shooting_goals_away', 'shooting_off_target_away', 'shooting_on_target_away', 'xg_shots_away', 'xg_total_team_xg_away']

In [29]:
df.isna().sum()

match_id                          0
general_aerial_duels_won_home    10
general_blocked_shots_home       10
general_clean_sheets_home        10
general_clearances_home          10
                                 ..
shooting_goals_away               9
shooting_off_target_away          9
shooting_on_target_away           9
xg_shots_away                     9
xg_total_team_xg_away            10
Length: 106, dtype: int64

In [34]:
from sqlalchemy import Table, MetaData, insert

metadata = MetaData()
metadata.reflect(bind=engine)

df = df.astype(object).where(pd.notna(df), None)


# Access any table like a dictionary
teams_table = metadata.tables['match_team_stats']

stmt = insert(teams_table).prefix_with("IGNORE").values(df.to_dict(orient='records'))

In [35]:
with engine.connect() as conn:
    conn.execute(stmt)
    conn.commit()

In [36]:
df

,match_id,general_aerial_duels_won_home,general_blocked_shots_home,general_clean_sheets_home,general_clearances_home,general_corners_home,general_expected_goals_home,general_fouls_home,general_goalkeeper_saves_home,general_goals_conceded_home,...,possession_71_75_away,possession_76_80_away,possession_81_85_away,possession_86_90_away,shooting_blocked_away,shooting_goals_away,shooting_off_target_away,shooting_on_target_away,xg_shots_away,xg_total_team_xg_away
0,43ba7695,6.0,4.0,0.0,6.0,9.0,3.0,12.0,3.0,3.0,...,50.28,61.16,43.51,34.91,2.0,3.0,2.0,6.0,10.0,2.0
1,85bb856a,14.0,1.0,0.0,3.0,2.0,2.0,16.0,1.0,4.0,...,57.37,40.05,74.32,41.92,3.0,4.0,1.0,5.0,9.0,1.7
2,588d481f,8.0,4.0,0.0,3.0,4.0,1.4,6.0,3.0,1.0,...,47.48,35.72,16.7,55.2,1.0,1.0,3.0,4.0,8.0,0.4
3,1b458adf,8.0,9.0,0.0,8.0,3.0,1.1,10.0,2.0,3.0,...,33.44,42.86,23.66,32.48,3.0,3.0,2.0,5.0,11.0,1.5
4,5bce4433,10.0,2.0,0.0,5.0,2.0,1.3,12.0,4.0,0.0,...,41.31,45.27,33.57,42.54,3.0,0.0,1.0,4.0,9.0,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,dee239a9,6.0,1.0,0.0,16.0,6.0,1.3,5.0,3.0,2.0,...,51.39,40.69,78.63,34.66,6.0,2.0,5.0,5.0,16.0,1.1
1041,eaff4742,10.0,5.0,0.0,10.0,12.0,2.6,12.0,3.0,0.0,...,40.48,46.65,32.17,15.81,3.0,0.0,6.0,3.0,12.0,1.2
1042,f5d62f89,10.0,4.0,0.0,12.0,10.0,1.8,13.0,2.0,0.0,...,45.98,46.59,54.37,60.45,1.0,0.0,3.0,2.0,8.0,0.4
1043,fc3f246b,32.0,2.0,0.0,3.0,11.0,1.4,20.0,2.0,1.0,...,46.79,52.76,47.75,40.09,2.0,1.0,2.0,3.0,7.0,0.8
1044,ff05beda,9.0,2.0,0.0,13.0,2.0,0.9,16.0,4.0,4.0,...,40.41,70.19,82.5,34.93,5.0,4.0,2.0,8.0,16.0,1.2

In [37]:
df.to_sql('match_team_stats', engine, if_exists='append', index=False)

1045