In [1]:
import pandas as pd
import glob
import os
from sqlalchemy import create_engine

db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'


engine = create_engine(db_string)

In [3]:
df = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/matches/feed/cleaned_mls_match_feeds3.csv')

df

,match_id,date,feed_id,minute,title,comment
0,bb7391b6,2026-03-08,38,15',Yellow Card,Ender Echenique (FC Cincinnati) is shown the y...
1,bb7391b6,2026-03-08,37,19',Attempt Saved,Attempt blocked. Dániel Sallói's (Toronto FC) ...
2,bb7391b6,2026-03-08,36,25',Yellow Card,Benjamín Kuscevic (Toronto FC) is shown the ye...
3,bb7391b6,2026-03-08,35,29',Attempt Saved,Attempt saved. Emilio Aristizábal's (Toronto F...
4,bb7391b6,2026-03-08,34,29',Attempt Missed,Attempt missed. Djordje Mihailovic's (Toronto ...
...,...,...,...,...,...,...
1562,dee239a9,2026-02-21,5,84',Substitution,"Substitution: Antony out, J. Ortiz in"
1563,dee239a9,2026-02-21,4,86',Attempt Missed,Attempt missed. Andrés Herrera's (Columbus Cre...
1564,dee239a9,2026-02-21,3,88',Attempt Saved,Attempt saved. Cole Bassett's (Portland Timber...
1565,dee239a9,2026-02-21,2,88',GOAL,Goal! 3:2. Ariel Lassiter (Portland Timbers) s...
1566,dee239a9,2026-02-21,1,90',Substitution,"Substitution: K. Velde out, I. Smith in"

In [4]:
df.rename(columns={'minute' : 'event_minute', 'title': 'event_type', 'comment' : 'event_comment'}, inplace=True)

In [5]:
df

,match_id,date,feed_id,event_minute,event_type,event_comment
0,bb7391b6,2026-03-08,38,15',Yellow Card,Ender Echenique (FC Cincinnati) is shown the y...
1,bb7391b6,2026-03-08,37,19',Attempt Saved,Attempt blocked. Dániel Sallói's (Toronto FC) ...
2,bb7391b6,2026-03-08,36,25',Yellow Card,Benjamín Kuscevic (Toronto FC) is shown the ye...
3,bb7391b6,2026-03-08,35,29',Attempt Saved,Attempt saved. Emilio Aristizábal's (Toronto F...
4,bb7391b6,2026-03-08,34,29',Attempt Missed,Attempt missed. Djordje Mihailovic's (Toronto ...
...,...,...,...,...,...,...
1562,dee239a9,2026-02-21,5,84',Substitution,"Substitution: Antony out, J. Ortiz in"
1563,dee239a9,2026-02-21,4,86',Attempt Missed,Attempt missed. Andrés Herrera's (Columbus Cre...
1564,dee239a9,2026-02-21,3,88',Attempt Saved,Attempt saved. Cole Bassett's (Portland Timber...
1565,dee239a9,2026-02-21,2,88',GOAL,Goal! 3:2. Ariel Lassiter (Portland Timbers) s...
1566,dee239a9,2026-02-21,1,90',Substitution,"Substitution: K. Velde out, I. Smith in"

In [6]:
df = df.rename(columns={'feed_id' : 'event_id'})

In [6]:
df

,date,event_id,event_minute,event_type,event_comment,home_team,away_team,match_id
0,2025-10-18,36,90'+7,Attempt Missed,Attempt missed. Nicolás Romero's (Minnesota Un...,LA,MIN,94412db9
1,2025-10-18,35,90'+7,Foul,Edwin Cerrillo (LA Galaxy) is shown the second...,LA,MIN,94412db9
2,2025-10-18,34,90'+5,Corner,Goal! 2:1. Joaquín Pereyra (Minnesota United F...,LA,MIN,94412db9
3,2025-10-18,33,89',Substitution,"Substitution: J. Paintsil out, T. Lepley in",LA,MIN,94412db9
4,2025-10-18,32,83',Attempt Saved,Attempt blocked. Joaquín Pereyra's (Minnesota ...,LA,MIN,94412db9
...,...,...,...,...,...,...,...,...
38652,2024-02-21,5,23',Attempt Saved,Attempt saved. Diego Gómez's (Inter Miami CF) ...,MIA,RSL,91a639d5
38653,2024-02-21,4,21',Attempt Saved,Attempt blocked. Lionel Messi's (Inter Miami C...,MIA,RSL,91a639d5
38654,2024-02-21,3,20',Attempt Saved,Attempt saved. Luis Suárez's (Inter Miami CF) ...,MIA,RSL,91a639d5
38655,2024-02-21,2,15',Foul,Pablo Ruiz (Real Salt Lake) is shown the yello...,MIA,RSL,91a639d5
38656,2024-02-21,1,6',Attempt Missed,Attempt missed. Luis Suárez's (Inter Miami CF)...,MIA,RSL,91a639d5

In [7]:
### organzise columns
df = df[['event_id','match_id', 'event_minute', 'event_type', 'event_comment']]

In [8]:
df.to_sql('match_events', engine, if_exists='append', index=False)

1567