In [1]:
from pathlib import Path
import pandas as pd
import glob
import re
from sqlalchemy import create_engine
import os

In [2]:
### combine csv files into one dataframe
files = glob.glob(r"G:\My Drive\GitHubProjects\MLS\data\interim\teams\teams_*.csv")


df = [] 

for file in files:
    df.append(pd.read_csv(file))

df = pd.concat(df, ignore_index=True)

df

,team_id,team_name,overall_score,attack,midfield,defense,worth_euro,num_players,lineup,style,date
0,112893,Inter Miami,72,78,74,70,NaN,26,4-4-2,Holding,2025-11-20
1,112996,Los Angeles FC,71,75,70,70,NaN,30,4-3-3,Holding,2025-11-20
2,101112,Vancouver Whitecaps FC,71,73,72,68,173.5,30,4-2-3-1,Wide,2025-11-20
3,113149,FC Cincinnati,71,73,71,69,226.5,28,3-4-2-1,NaN,2025-11-20
4,111138,Minnesota United FC,70,71,70,68,150.0,23,5-4-1,Flat,2025-11-20
...,...,...,...,...,...,...,...,...,...,...,...
19090,111065,Real Salt Lake,66,66,68,66,171.5,20,4-2-3-1,Wide,2026-02-18
19091,112606,Orlando City SC,66,68,67,64,225.5,18,4-4-1-1,Midfield,2026-02-18
19092,111928,San Jose Earthquakes,65,63,66,63,162.8,20,3-4-3,Flat,2026-02-18
19093,689,New York Red Bulls,65,75,67,64,261.0,22,4-2-3-1,Wide,2026-02-18
19094,696,Sporting Kansas City,63,67,64,59,182.5,19,4-2-3-1,Wide,2026-02-18

In [3]:
df.to_csv(r"G:\My Drive\GitHubProjects\MLS\data\interim\teams\master_teams_0326.csv", index=False)

In [4]:
master = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/teams/master_teams_0326.csv')

In [5]:
master.head()

,team_id,team_name,overall_score,attack,midfield,defense,worth_euro,num_players,lineup,style,date
0,112893,Inter Miami,72,78,74,70,NaN,26,4-4-2,Holding,2025-11-20
1,112996,Los Angeles FC,71,75,70,70,NaN,30,4-3-3,Holding,2025-11-20
2,101112,Vancouver Whitecaps FC,71,73,72,68,173.5,30,4-2-3-1,Wide,2025-11-20
3,113149,FC Cincinnati,71,73,71,69,226.5,28,3-4-2-1,NaN,2025-11-20
4,111138,Minnesota United FC,70,71,70,68,150.0,23,5-4-1,Flat,2025-11-20

In [6]:
## move date column to first position

cols = master.columns.tolist()
cols.insert(0, cols.pop(cols.index('date')))
master = master[cols]
  
master.head()

,date,team_id,team_name,overall_score,attack,midfield,defense,worth_euro,num_players,lineup,style
0,2025-11-20,112893,Inter Miami,72,78,74,70,NaN,26,4-4-2,Holding
1,2025-11-20,112996,Los Angeles FC,71,75,70,70,NaN,30,4-3-3,Holding
2,2025-11-20,101112,Vancouver Whitecaps FC,71,73,72,68,173.5,30,4-2-3-1,Wide
3,2025-11-20,113149,FC Cincinnati,71,73,71,69,226.5,28,3-4-2-1,NaN
4,2025-11-20,111138,Minnesota United FC,70,71,70,68,150.0,23,5-4-1,Flat

In [7]:
### rename lineup and style to formation_base and formation_style

master = master.rename(columns={'lineup': 'formation_base', 'style': 'formation_style', 'overall_score': 'overall', 'defense': 'defence', 'worth_euro': 'club_worth'})

In [8]:
### make date column datetime type

master['date'] = pd.to_datetime(master['date'])

In [9]:
master

,date,team_id,team_name,overall,attack,midfield,defence,club_worth,num_players,formation_base,formation_style
0,2025-11-20,112893,Inter Miami,72,78,74,70,NaN,26,4-4-2,Holding
1,2025-11-20,112996,Los Angeles FC,71,75,70,70,NaN,30,4-3-3,Holding
2,2025-11-20,101112,Vancouver Whitecaps FC,71,73,72,68,173.5,30,4-2-3-1,Wide
3,2025-11-20,113149,FC Cincinnati,71,73,71,69,226.5,28,3-4-2-1,NaN
4,2025-11-20,111138,Minnesota United FC,70,71,70,68,150.0,23,5-4-1,Flat
...,...,...,...,...,...,...,...,...,...,...,...
19090,2026-02-18,111065,Real Salt Lake,66,66,68,66,171.5,20,4-2-3-1,Wide
19091,2026-02-18,112606,Orlando City SC,66,68,67,64,225.5,18,4-4-1-1,Midfield
19092,2026-02-18,111928,San Jose Earthquakes,65,63,66,63,162.8,20,3-4-3,Flat
19093,2026-02-18,689,New York Red Bulls,65,75,67,64,261.0,22,4-2-3-1,Wide
19094,2026-02-18,696,Sporting Kansas City,63,67,64,59,182.5,19,4-2-3-1,Wide

In [10]:
## rename team_name to name

master = master.rename(columns={'team_name': 'name', 'num_players': 'players'})

In [11]:
### drop name 
master = master.drop(columns=['name'])

In [12]:
db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [17]:
master.to_sql('team_stats', con=engine, if_exists='append', index=False)

19095