In [1]:
# pip install pandas python-dateutil unidecode sqlalchemy
import re
import os
import pandas as pd
import numpy as np
from unidecode import unidecode
from sqlalchemy import create_engine

In [2]:
df = pd.read_csv(r"G://My Drive/GitHubProjects/MLS/data/interim/players/cleaned_master_players_w_team_abbr_post031626_full.csv")
OUTPUT_DIR  = r"G://My Drive/GitHubProjects/MLS/data/interim/players/sql_players_0326_full"
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [3]:
def read_master(path_or_df) -> pd.DataFrame:
    if isinstance(path_or_df, pd.DataFrame):
        df = path_or_df.copy()
    else:
        df = pd.read_csv(path_or_df, low_memory=False)

    # fix encoding issues in team name (e.g. CF MontrÃ©al -> CF Montreal)
    df["team_abbr"] = df["team_abbr"].apply(
        lambda x: unidecode(str(x)).strip() if pd.notna(x) else x
    )

    # parse snap date from the 'date' column
    df["snap_date"] = pd.to_datetime(df["date"], infer_datetime_format=True)

    # clean up player id
    df["player_id"] = pd.to_numeric(df["id"], errors="coerce").astype("Int64")
    df = df.dropna(subset=["player_id"]).astype({"player_id": "int64"})

    # contract years as nullable int
    for c in ["contract_start", "contract_end"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce").astype("Int64")

    return df

In [4]:
def build_snapshots(df: pd.DataFrame) -> pd.DataFrame:
    """One row per (snap_date, player_id) with team info."""
    keep = ["snap_date", "player_id", "team_abbr",
            "contract_start", "contract_end"]
    keep = [c for c in keep if c in df.columns]
    snap = (
        df[keep]
        .drop_duplicates(subset=["snap_date", "player_id"])
        .sort_values(["player_id", "snap_date"])
        .reset_index(drop=True)
    )
    return snap

In [5]:
def compute_first_seen(snap: pd.DataFrame) -> pd.DataFrame:
    return (
        snap.groupby("player_id", as_index=False)["snap_date"]
            .min()
            .rename(columns={"snap_date": "first_seen"})
    )

In [6]:
def compute_stints(snap: pd.DataFrame) -> pd.DataFrame:
    """Detect continuous spells at each team."""
    s = snap.sort_values(["player_id", "snap_date"]).copy()
    s["prev_team"] = s.groupby("player_id")["team_abbr"].shift()
    s["jump"] = (s["team_abbr"] != s["prev_team"]).astype(int)
    s.loc[s.groupby("player_id").head(1).index, "jump"] = 1
    s["stint_id"] = s.groupby("player_id")["jump"].cumsum()

    stints = (
        s.groupby(["player_id", "stint_id", "team_abbr"])
         .agg(
             stint_start=("snap_date", "min"),
             stint_end=("snap_date", "max"),
             days_observed=("snap_date", lambda x: (x.max() - x.min()).days + 1),
             obs_count=("snap_date", "count")
         )
         .reset_index()
         .sort_values(["player_id", "stint_start"])
    )
    return stints

In [7]:
def compute_transfers(stints: pd.DataFrame) -> pd.DataFrame:
    """Identify team changes from stint-to-stint."""
    st = stints.sort_values(["player_id", "stint_start"]).copy()
    st["next_team"]  = st.groupby("player_id")["team_abbr"].shift(-1)
    st["next_start"] = st.groupby("player_id")["stint_start"].shift(-1)
    if "team_abbr" in st.columns:
        st["next_abbr"] = st.groupby("player_id")["team_abbr"].shift(-1)

    transfers = st[(st["next_team"].notna()) & (st["team_abbr"] != st["next_team"])].copy()
    transfers = transfers.rename(columns={
        "team_abbr":   "from_team",
        "stint_start": "from_start",
        "stint_end":   "from_end",
        "next_team":   "to_team",
        "next_start":  "transfer_date"
    })

    out_cols = ["player_id", "from_team", "to_team", "from_start", "from_end", "transfer_date"]
    if "team_abbr" in transfers.columns:
        transfers = transfers.rename(columns={"team_abbr": "from_abbr", "next_abbr": "to_abbr"})
        out_cols = ["player_id", "from_team", "from_abbr", "to_team", "to_abbr",
                    "from_start", "from_end", "transfer_date"]

    return transfers[[c for c in out_cols if c in transfers.columns]]

In [8]:
def compute_last_seen_and_inactive(snap: pd.DataFrame, gap_days: int = 60) -> pd.DataFrame:
    last = (
        snap.groupby("player_id", as_index=False)["snap_date"]
            .max()
            .rename(columns={"snap_date": "last_seen"})
    )
    global_max = snap["snap_date"].max()
    last["inactive_flag"] = last["last_seen"] <= (global_max - pd.Timedelta(days=gap_days))
    last["as_of"] = global_max
    return last

In [9]:
def build_player_attributes(df: pd.DataFrame) -> pd.DataFrame:
    """
    One row per (player_id, snap_date) with all FIFA-style attribute columns.
    Useful for tracking rating/value/physical changes over time.
    """
    attr_cols = [
        "player_id", "snap_date", "name", "age", "height_cm", "weight_kg",
        "position", "foot", "jersey_num", "wage_eur", "value_eur",
        "overall_rating", "best_overall", "best_position",
        "total_attacking", "crossing", "finishing", "heading_accuracy",
        "short_passing", "volleys",
        "total_skill", "dribbling", "curve", "fk_accuracy", "long_passing", "ball_control",
        "total_movement", "acceleration", "sprint_speed", "agility", "reactions", "balance",
        "total_power", "shot_power", "jumping", "stamina", "long_shots",
        "total_mentality", "aggression", "interceptions", "attack_position",
        "vision", "penalties", "composure",
        "total_defending", "defensive_awareness", "standing_tackle", "sliding_tackle",
        "total_goalkeeping", "gk_diving", "gk_handling", "gk_kicking",
        "gk_positioning", "gk_reflexes"
    ]
    attr_cols = [c for c in attr_cols if c in df.columns]
    return (
        df[attr_cols]
        .drop_duplicates(subset=["player_id", "snap_date"])
        .sort_values(["player_id", "snap_date"])
        .reset_index(drop=True)
    )

In [10]:
def upload_to_mysql(df: pd.DataFrame, table: str, engine, if_exists: str = "append") -> None:
    """Upload a DataFrame to MySQL, skipping rows with existing primary keys."""
    existing_ids = set(pd.read_sql(f"SELECT player_id FROM {table}", engine)["player_id"])
    new_rows = df[~df["player_id"].isin(existing_ids)]
    if len(new_rows) == 0:
        print(f"[skip] {table}: no new rows to upload")
        return
    new_rows.to_sql(table, engine, if_exists=if_exists, index=False)
    print(f"[ok] {table}: uploaded {len(new_rows):,} new rows")

In [11]:
if __name__ == "__main__":
    master = read_master(df)
    print(f"[ok] master loaded: {len(master):,} rows, {master['player_id'].nunique():,} unique players")

    # --- roster snapshots (team + date per player) ---
    snapshots = build_snapshots(master)
    snapshots.to_parquet(os.path.join(OUTPUT_DIR, "roster_snapshots.parquet"), index=False)
    snapshots.to_csv(os.path.join(OUTPUT_DIR, "roster_snapshots.csv"), index=False)
    print(f"[ok] snapshots: {len(snapshots):,} rows")

    # --- first seen ---
    first_seen = compute_first_seen(snapshots)
    first_seen.to_csv(os.path.join(OUTPUT_DIR, "first_seen.csv"), index=False)
    print(f"[ok] first_seen: {len(first_seen):,} rows")

    # --- stints ---
    stints = compute_stints(snapshots)
    stints.to_csv(os.path.join(OUTPUT_DIR, "stints.csv"), index=False)
    print(f"[ok] stints: {len(stints):,} rows")

    # --- transfers ---
    transfers = compute_transfers(stints)
    transfers.to_csv(os.path.join(OUTPUT_DIR, "transfers.csv"), index=False)
    print(f"[ok] transfers: {len(transfers):,} rows")

    # --- last seen / inactive flag ---
    last_seen = compute_last_seen_and_inactive(snapshots, gap_days=60)
    last_seen.to_csv(os.path.join(OUTPUT_DIR, "last_seen_60day_inactive.csv"), index=False)
    print(f"[ok] last_seen: {len(last_seen):,} rows")

    # --- player attributes (ratings, value, physical) ---
    attributes = build_player_attributes(master)
    attributes.to_parquet(os.path.join(OUTPUT_DIR, "player_attributes.parquet"), index=False)
    attributes.to_csv(os.path.join(OUTPUT_DIR, "player_attributes.csv"), index=False)
    print(f"[ok] attributes: {len(attributes):,} rows")

C:\Users\diffe\AppData\Local\Temp\ipykernel_31224\1047005526.py:13: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df["snap_date"] = pd.to_datetime(df["date"], infer_datetime_format=True)

[ok] master loaded: 1,014,650 rows, 4,012 unique players
[ok] snapshots: 508,383 rows
[ok] first_seen: 4,012 rows
[ok] stints: 5,956 rows
[ok] transfers: 1,944 rows
[ok] last_seen: 4,012 rows
[ok] attributes: 508,383 rows

In [12]:
stints = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/players/sql_players_0326_full/stints.csv')

In [13]:
stints

,player_id,stint_id,team_abbr,stint_start,stint_end,days_observed,obs_count
0,250,1,LA,2007-08-30,2012-08-31,1829,9
1,330,1,LA,2011-08-30,2016-11-21,1911,216
2,432,1,CLB,2007-08-30,2008-08-30,367,3
3,432,2,LA,2009-02-22,2009-08-30,190,2
4,432,3,PHI,2010-08-30,2011-08-30,366,3
...,...,...,...,...,...,...,...
5951,279787,1,DC,2024-01-30,2026-03-10,771,83
5952,279937,1,ATX,2024-01-31,2026-03-10,770,70
5953,279938,1,POR,2026-01-07,2026-03-10,63,10
5954,279941,1,RSL,2024-01-31,2025-04-01,427,52
5955,279942,1,ATX,2024-02-08,2026-03-10,762,86

In [14]:
teams = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/interim/teams/master_teams.csv')

print('teams and their ids:', teams[['team_name', 'team_id']].drop_duplicates().sort_values('team_id'))

teams and their ids:                     team_name  team_id
8               Columbus Crew      687
27                  DC United      688
13         New York Red Bulls      689
14     New England Revolution      691
15               Chicago Fire      693
23            Colorado Rapids      694
28                  FC Dallas      695
24       Sporting Kansas City      696
9                   LA Galaxy      697
16             Houston Dynamo      698
2      Vancouver Whitecaps FC   101112
25             Real Salt Lake   111065
15774              Chivas USA   111070
4         Minnesota United FC   111138
29                CF Montréal   111139
5            Portland Timbers   111140
6         Seattle Sounders FC   111144
26                 Toronto FC   111651
21       San Jose Earthquakes   111928
12         Philadelphia Union   112134
18            Orlando City SC   112606
17           New York City FC   112828
11             Atlanta United   112885
0                 Inter Miami   112893
1              Los Angeles FC   112996
22          St. Louis CITY SC   113018
3               FC Cincinnati   113149
19                  Austin FC   114161
20               Nashville SC   114162
10               Charlotte FC   114640
7                San Diego FC   131439

In [15]:
teams_dict = {
    'Inter Miami': 'MIA',
    'Seattle Sounders FC': 'SEA',
    'Los Angeles FC': 'LAFC',
    'LA Galaxy': 'LA',
    'St. Louis CITY SC': 'STL',
    'Charlotte FC': 'CLT',
    'Atlanta United': 'ATL',
    'FC Cincinnati': 'CIN',
    'Portland Timbers': 'POR',
    'San Jose Earthquakes': 'SJ',
    'Columbus Crew': 'CLB',
    'New York Red Bulls': 'RBNY',
    'New England Revolution': 'NE',
    'Houston Dynamo': 'HOU',
    'Orlando City SC': 'ORL',
    'Austin FC': 'ATX',
    'Nashville SC': 'NSH',
    'Vancouver Whitecaps FC': 'VAN',
    'Philadelphia Union': 'PHI',
    'Minnesota United FC': 'MIN',
    'Toronto FC': 'TOR',
    'Chicago Fire': 'CHI',
    'FC Dallas': 'DAL',
    'Sporting Kansas City': 'SKC',
    'Real Salt Lake': 'RSL',
    'DC United': 'DC',
    'Colorado Rapids': 'COL',
    'New York City FC': 'NYC',
    'CF Montréal': 'MTL',
    'San Diego FC': 'SD',
}

### reverse dict then use it to make team_name column in stints df to match teams df and get team ids
reverse_teams_dict = {v: k for k, v in teams_dict.items()}  
###use dict to replace team abbr with team name in stints df to match teams df and get team ids

In [16]:
df5 = stints.copy()
df5['team_abbr'] = df5['team_abbr'].replace(reverse_teams_dict)

In [17]:
df5.head()

,player_id,stint_id,team_abbr,stint_start,stint_end,days_observed,obs_count
0,250,1,LA Galaxy,2007-08-30,2012-08-31,1829,9
1,330,1,LA Galaxy,2011-08-30,2016-11-21,1911,216
2,432,1,Columbus Crew,2007-08-30,2008-08-30,367,3
3,432,2,LA Galaxy,2009-02-22,2009-08-30,190,2
4,432,3,Philadelphia Union,2010-08-30,2011-08-30,366,3

In [18]:
df5 = df5.rename(columns={'team_abbr': 'team_name'})

In [19]:
df5.head()

,player_id,stint_id,team_name,stint_start,stint_end,days_observed,obs_count
0,250,1,LA Galaxy,2007-08-30,2012-08-31,1829,9
1,330,1,LA Galaxy,2011-08-30,2016-11-21,1911,216
2,432,1,Columbus Crew,2007-08-30,2008-08-30,367,3
3,432,2,LA Galaxy,2009-02-22,2009-08-30,190,2
4,432,3,Philadelphia Union,2010-08-30,2011-08-30,366,3

In [22]:
#### remove dupe team ids

teams = teams.drop_duplicates(subset=['team_id'], keep='first')

print('teams and their ids:', teams[['team_name', 'team_id']].drop_duplicates().sort_values('team_id'))

teams and their ids:                     team_name  team_id
8               Columbus Crew      687
27                  DC United      688
13         New York Red Bulls      689
14     New England Revolution      691
15               Chicago Fire      693
23            Colorado Rapids      694
28                  FC Dallas      695
24       Sporting Kansas City      696
9                   LA Galaxy      697
16             Houston Dynamo      698
2      Vancouver Whitecaps FC   101112
25             Real Salt Lake   111065
15774              Chivas USA   111070
4         Minnesota United FC   111138
29                CF Montreal   111139
5            Portland Timbers   111140
6         Seattle Sounders FC   111144
26                 Toronto FC   111651
21       San Jose Earthquakes   111928
12         Philadelphia Union   112134
18            Orlando City SC   112606
17           New York City FC   112828
11             Atlanta United   112885
0                 Inter Miami   112893
1              Los Angeles FC   112996
22          St. Louis CITY SC   113018
3               FC Cincinnati   113149
19                  Austin FC   114161
20               Nashville SC   114162
10               Charlotte FC   114640
7                San Diego FC   131439

In [23]:
## remove accents from team names in teams df to match stints team names

teams = teams.copy()
teams['team_name'] = teams['team_name'].apply(lambda x: unidecode(str(x)).strip() if pd.notna(x) else x)

print('teams and their ids:', teams[['team_name', 'team_id']].drop_duplicates().sort_values('team_id'))

teams and their ids:                     team_name  team_id
8               Columbus Crew      687
27                  DC United      688
13         New York Red Bulls      689
14     New England Revolution      691
15               Chicago Fire      693
23            Colorado Rapids      694
28                  FC Dallas      695
24       Sporting Kansas City      696
9                   LA Galaxy      697
16             Houston Dynamo      698
2      Vancouver Whitecaps FC   101112
25             Real Salt Lake   111065
15774              Chivas USA   111070
4         Minnesota United FC   111138
29                CF Montreal   111139
5            Portland Timbers   111140
6         Seattle Sounders FC   111144
26                 Toronto FC   111651
21       San Jose Earthquakes   111928
12         Philadelphia Union   112134
18            Orlando City SC   112606
17           New York City FC   112828
11             Atlanta United   112885
0                 Inter Miami   112893
1              Los Angeles FC   112996
22          St. Louis CITY SC   113018
3               FC Cincinnati   113149
19                  Austin FC   114161
20               Nashville SC   114162
10               Charlotte FC   114640
7                San Diego FC   131439

In [25]:
df6 = df5.merge(teams[['team_id', 'team_name']], on='team_name', how='left')

print('teams and their ids:', df6[['team_name', 'team_id']].drop_duplicates().sort_values('team_id'))

teams and their ids:                   team_name   team_id
2             Columbus Crew     687.0
9                 DC United     688.0
10       New York Red Bulls     689.0
6    New England Revolution     691.0
7              Chicago Fire     693.0
36          Colorado Rapids     694.0
18                FC Dallas     695.0
40     Sporting Kansas City     696.0
0                 LA Galaxy     697.0
128          Houston Dynamo     698.0
8    Vancouver Whitecaps FC  101112.0
23           Real Salt Lake  111065.0
289     Minnesota United FC  111138.0
31         Portland Timbers  111140.0
32      Seattle Sounders FC  111144.0
19               Toronto FC  111651.0
21     San Jose Earthquakes  111928.0
4        Philadelphia Union  112134.0
304         Orlando City SC  112606.0
30         New York City FC  112828.0
288          Atlanta United  112885.0
318             Inter Miami  112893.0
253          Los Angeles FC  112996.0
342       St. Louis CITY SC  113018.0
443           FC Cincinnati  113149.0
307               Austin FC  114161.0
285            Nashville SC  114162.0
296            Charlotte FC  114640.0
284            San Diego FC  131439.0
5               CF Montréal       NaN

In [28]:
print('nan team id count:', df6['team_id'].isna().sum())
df6.head()

nan team id count: 209

,player_id,stint_id,team_name,stint_start,stint_end,days_observed,obs_count,team_id
0,250,1,LA Galaxy,2007-08-30,2012-08-31,1829,9,697.0
1,330,1,LA Galaxy,2011-08-30,2016-11-21,1911,216,697.0
2,432,1,Columbus Crew,2007-08-30,2008-08-30,367,3,687.0
3,432,2,LA Galaxy,2009-02-22,2009-08-30,190,2,697.0
4,432,3,Philadelphia Union,2010-08-30,2011-08-30,366,3,112134.0

In [30]:
print('team names with nan ids:', df6[df6['team_id'].isna()]['team_name'].unique())

team names with nan ids: ['CF Montréal']

In [31]:
### put team_id '111139' for cf montreal

df6.loc[df6['team_name'] == 'CF Montréal', 'team_id'] = 111139

In [32]:
print('team names with nan ids:', df6[df6['team_id'].isna()]['team_name'].unique())

team names with nan ids: []

In [34]:
stints = df6.drop(columns=['team_name'])

stints

,player_id,stint_id,stint_start,stint_end,days_observed,obs_count,team_id
0,250,1,2007-08-30,2012-08-31,1829,9,697.0
1,330,1,2011-08-30,2016-11-21,1911,216,697.0
2,432,1,2007-08-30,2008-08-30,367,3,687.0
3,432,2,2009-02-22,2009-08-30,190,2,697.0
4,432,3,2010-08-30,2011-08-30,366,3,112134.0
...,...,...,...,...,...,...,...
5951,279787,1,2024-01-30,2026-03-10,771,83,688.0
5952,279937,1,2024-01-31,2026-03-10,770,70,114161.0
5953,279938,1,2026-01-07,2026-03-10,63,10,111140.0
5954,279941,1,2024-01-31,2025-04-01,427,52,111065.0
5955,279942,1,2024-02-08,2026-03-10,762,86,114161.0

In [35]:
from sqlalchemy import create_engine

db_string = 'mysql+pymysql://root:!wMoU9lBdLZWW6Y8@o8ukkP9TliImN.h.filess.io:58202/MLS'

engine = create_engine(db_string)

In [36]:
stints.to_sql(name='team_roster', con=engine, if_exists='append', index=False)

5956