In [46]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException, NoSuchElementException, WebDriverException
import time
import hashlib
from bs4 import BeautifulSoup

In [47]:
options = Options()
options.add_argument('--disable-gpu')
options.add_argument('--no-sandbox')
options.add_argument('--disable-infobars')  
options.add_argument('--disable-extensions')
options.add_argument('--disable-notifications')

service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=options)

In [48]:
def dismiss_cookies(driver, timeout=8):
    wait = WebDriverWait(driver, timeout)
    tried = []

    def _visible(el):
        try:
            return el.is_displayed() and el.is_enabled()
        except Exception:
            return False

    # 0) Give the banner a second to mount
    driver.execute_script("window._probe = Date.now();")
    try:
        wait.until(
            EC.presence_of_all_elements_located((By.CSS_SELECTOR, "body")))
    except TimeoutException:
        pass

    # 1) Direct hit: common OneTrust IDs/classes
    candidates = [
        (By.ID, "onetrust-accept-btn-handler"),
        (By.CSS_SELECTOR, "button#onetrust-accept-btn-handler"),
        (By.CSS_SELECTOR,
         "#onetrust-banner-sdk button#onetrust-accept-btn-handler"),
        (By.CSS_SELECTOR, "button#onetrust-reject-all-handler"
         ),  # sometimes only Reject is visible first
        (By.CSS_SELECTOR, "[data-testid='onetrust-accept-btn-handler']"),
        (By.XPATH,
         "//button[contains(@id,'accept') and contains(translate(., 'ACEPT','acept'),'accept')]"
         ),
        (By.XPATH,
         "//button[contains(@aria-label,'Accept') or contains(normalize-space(.),'Accept')]"
         ),
    ]
    for how, what in candidates:
        tried.append(f"{how}={what}")
        try:
            btn = driver.find_element(how, what)
            if _visible(btn):
                btn.click()
                return True
        except NoSuchElementException:
            continue
        except WebDriverException:
            # Try JS click if the element exists but normal click fails
            try:
                driver.execute_script("arguments[0].click();", btn)
                return True
            except Exception:
                continue

    # 2) If not found, check for a banner container (present but hidden/animating)
    try:
        banner = driver.find_element(By.ID, "onetrust-banner-sdk")
        if _visible(banner):
            try:
                btn = banner.find_element(By.CSS_SELECTOR,
                                          "button[id*='accept']")
                driver.execute_script("arguments[0].click();", btn)
                return True
            except Exception:
                pass
    except NoSuchElementException:
        pass

    # 3)Scan iframes and try inside.
    iframes = driver.find_elements(By.TAG_NAME, "iframe")
    for i, frame in enumerate(iframes):
        # quick filter to avoid costly switches
        src = (frame.get_attribute("src") or "").lower()
        name = (frame.get_attribute("name") or "").lower()
        if any(k in src + name
               for k in ("consent", "onetrust", "privacy", "cookie")):
            tried.append(f"iframe[{i}] src={src or name}")
            try:
                driver.switch_to.frame(frame)
                # try common selectors again inside this frame
                for how, what in candidates:
                    try:
                        btn = WebDriverWait(driver, 2).until(
                            EC.presence_of_element_located((how, what)))
                        if _visible(btn):
                            driver.execute_script(
                                "arguments[0].scrollIntoView({block:'center'});",
                                btn)
                            try:
                                btn.click()
                            except Exception:
                                driver.execute_script("arguments[0].click();",
                                                      btn)
                            driver.switch_to.default_content()
                            return True
                    except Exception:
                        continue
                driver.switch_to.default_content()
            except Exception:
                # ensure we’re back
                try:
                    driver.switch_to.default_content()
                except:
                    pass

    # 4) Last resort: call OneTrust API if it exists, or remove the banner to unblock clicks
    try:
        ok = driver.execute_script("""
            if (window.OneTrust && OneTrust.AcceptAll) { OneTrust.AcceptAll(); return true; }
            const b = document.getElementById('onetrust-banner-sdk');
            if (b) { b.remove(); return 'removed'; }
            return false;
        """)
        if ok:
            return True
    except Exception:
        pass

    print("[cookies] Could not find/close cookie banner. Tried:",
          *tried,
          sep="\n - ")
    return False

In [49]:
url = 'https://www.mlssoccer.com/schedule/scores#competition=MLS-COM-000001&club=all'
driver.get(url)
wait = WebDriverWait(driver, 15)

try:
    dismiss_cookies(driver, timeout=8)
except:
    print("Cookie button not found or already clicked.")

rounds = 5
matches = []
stop_reached = False

for i in range(rounds):
    if stop_reached:
        break

    try:
        wait.until(EC.presence_of_element_located((By.CLASS_NAME, 'mls-c-schedule__matches')))
        time.sleep(2)

        soup = BeautifulSoup(driver.page_source, "html.parser")
        schedule = soup.find("div", class_="mls-c-schedule__matches")

        if not schedule:
            print(f"Round {i+1}: No matches table found")
        else:
            for match_link in schedule.find_all("a", href=True):

                # Resolve date by walking up DOM to nearest h2
                date_text = None
                for parent in match_link.parents:
                    h2 = parent.find_previous_sibling("h2") or parent.find("h2")
                    if h2:
                        date_text = h2.get_text(strip=True)
                        break

                if not date_text:
                    continue
                
                link = match_link['href']

                home_div = match_link.find("div", class_=lambda c: c and "mls-c-club" in c and "--home" in c)
                away_div = match_link.find("div", class_=lambda c: c and "mls-c-club" in c and "--away" in c)
                scores = match_link.find_all("span", class_="mls-c-scorebug__score")

                if not home_div or not away_div or len(scores) < 2:
                    continue

                home_abbr = home_div.find("span", class_="mls-c-club__abbreviation")
                away_abbr = away_div.find("span", class_="mls-c-club__abbreviation")

                if not home_abbr or not away_abbr:
                    continue

                home_team = home_abbr.get_text(strip=True)
                away_team = away_abbr.get_text(strip=True)
                home_score = scores[0].get_text(strip=True)
                away_score = scores[1].get_text(strip=True)

                match_id = hashlib.md5(
                    f"{home_team}_{away_team}_{date_text}".lower().replace(" ", "_").replace(",", "").encode()
                ).hexdigest()[:8]

                print(f"{date_text}: {home_team} {home_score}-{away_score} {away_team} | id: {match_id}")
                matches.append({
                    "date": date_text,
                    "home_team": home_team,
                    "away_team": away_team,
                    "home_score": home_score,
                    "away_score": away_score,
                    "match_id": match_id,
                    'link': link
                })

        if not stop_reached:
            old_table = driver.find_element(By.CLASS_NAME, 'mls-c-schedule__matches')
            previous_button = wait.until(EC.element_to_be_clickable((By.XPATH, "//button[@aria-label='Previous results']")))
            previous_button.click()
            wait.until(EC.staleness_of(old_table))

    except Exception as e:
        print(f"Round {i+1} error: {e}")

print(f"Total matches collected: {len(matches)}")
driver.quit()

Today, Mar 14: TOR 0-0 RBNY | id: 733c93f2
Round 1 error: Message:

Saturday Mar 7: NYC 5-0 ORL | id: 8865ae2a
Saturday Mar 7: DC 1-2 MIA | id: 0c956f37
Saturday Mar 7: ATL 2-3 RSL | id: b0713dc5
Saturday Mar 7: CLT 3-1 ATX | id: 646c3889
Saturday Mar 7: CLB 0-0 CHI | id: 5291010f
Saturday Mar 7: PHI 0-1 SJ | id: 3991a1bb
Saturday Mar 7: SKC 0-1 SD | id: f1fd2f24
Saturday Mar 7: NSH 3-1 MIN | id: dbcc55cf
Saturday Mar 7: STL 0-1 SEA | id: 29662ef7
Saturday Mar 7: COL 4-1 LA | id: e8e41c6d
Saturday Mar 7: LAFC 1-0 DAL | id: ab677e15
Saturday Mar 7: POR 1-4 VAN | id: 679970bf
Sunday Mar 8: RBNY 0-3 MTL | id: bc090e7f
Sunday Mar 8: CIN 0-1 TOR | id: 1d8589b6
Round 2 error: Message:

Saturday Feb 28: CHI 3-0 MTL | id: 2677b200
Saturday Feb 28: RBNY 1-0 NE | id: 696e062e
Saturday Feb 28: COL 2-0 POR | id: 9932553a
Saturday Feb 28: MIN 1-0 CIN | id: ccc1ebe1
Saturday Feb 28: RSL 2-1 SEA | id: c123bdf2
Saturday Feb 28: SJ 2-0 ATL | id: 5924fd44
Saturday Feb 28: DAL 0-0 NSH | id: 19a7b817
Saturday Feb 28: HOU 0-2 LAFC | id: a52dabed
Saturday Feb 28: SKC 2-2 CLB | id: 775e1f69
Saturday Feb 28: VAN 3-0 TOR | id: 68a62bb0
Saturday Feb 28: LA 3-0 CLT | id: 708a4133
Sunday Mar 1: ATX 1-0 DC | id: ce9a56f3
Sunday Mar 1: PHI 1-2 NYC | id: fdf75599
Sunday Mar 1: ORL 2-4 MIA | id: 99726934
Sunday Mar 1: SD 2-0 STL | id: 8317cb19
Round 3 error: Message:

Saturday Feb 21: STL 1-1 CLT | id: 95ee8e18
Saturday Feb 21: CIN 2-0 ATL | id: 3fe21bbf
Saturday Feb 21: DC 1-0 PHI | id: 0c970002
Saturday Feb 21: ORL 1-2 RBNY | id: 36ada33a
Saturday Feb 21: VAN 1-0 RSL | id: 31608e02
Saturday Feb 21: ATX 2-2 MIN | id: adfb093f
Saturday Feb 21: DAL 3-2 TOR | id: f45d88a5
Saturday Feb 21: HOU 2-1 CHI | id: ed610e2c
Saturday Feb 21: NSH 4-1 NE | id: 1a13ae26
Saturday Feb 21: LAFC 3-0 MIA | id: b5d3f6dd
Saturday Feb 21: POR 3-2 CLB | id: a2d28725
Saturday Feb 21: SD 5-0 MTL | id: e138c719
Saturday Feb 21: SJ 3-0 SKC | id: 9a5ab6be
Sunday Feb 22: LA 1-1 NYC | id: f6e2b863
Sunday Feb 22: SEA 2-0 COL | id: 890188eb
Round 4 error: Message:

Round 5 error: Message:

Total matches collected: 45

In [50]:
matches_df = pd.DataFrame(matches)

In [51]:
matches_df

,date,home_team,away_team,home_score,away_score,match_id,link
0,"Today, Mar 14",TOR,RBNY,0,0,733c93f2,https://www.mlssoccer.com/competitions/mls-reg...
1,Saturday Mar 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,Saturday Mar 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,Saturday Mar 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,Saturday Mar 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,Saturday Mar 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
6,Saturday Mar 7,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
7,Saturday Mar 7,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
8,Saturday Mar 7,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
9,Saturday Mar 7,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
10,Saturday Mar 7,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
11,Saturday Mar 7,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
12,Saturday Mar 7,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
13,Sunday Mar 8,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
14,Sunday Mar 8,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
15,Saturday Feb 28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
16,Saturday Feb 28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
17,Saturday Feb 28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
18,Saturday Feb 28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
19,Saturday Feb 28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
20,Saturday Feb 28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
21,Saturday Feb 28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
22,Saturday Feb 28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
23,Saturday Feb 28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
24,Saturday Feb 28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
25,Saturday Feb 28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
26,Sunday Mar 1,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
27,Sunday Mar 1,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
28,Sunday Mar 1,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
29,Sunday Mar 1,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
30,Saturday Feb 21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
31,Saturday Feb 21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
32,Saturday Feb 21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
33,Saturday Feb 21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
34,Saturday Feb 21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
35,Saturday Feb 21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
36,Saturday Feb 21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
37,Saturday Feb 21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
38,Saturday Feb 21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
39,Saturday Feb 21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
40,Saturday Feb 21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
41,Saturday Feb 21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
42,Saturday Feb 21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
43,Sunday Feb 22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
44,Sunday Feb 22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [52]:
### delete Today, Mar 14 from df

matches_df = matches_df[~matches_df['date'].str.contains("Today, Mar 14")]

In [54]:
matches_df

,date,home_team,away_team,home_score,away_score,match_id,link
1,Saturday Mar 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,Saturday Mar 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,Saturday Mar 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,Saturday Mar 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,Saturday Mar 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
6,Saturday Mar 7,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
7,Saturday Mar 7,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
8,Saturday Mar 7,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
9,Saturday Mar 7,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
10,Saturday Mar 7,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
11,Saturday Mar 7,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
12,Saturday Mar 7,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
13,Sunday Mar 8,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
14,Sunday Mar 8,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
15,Saturday Feb 28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
16,Saturday Feb 28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
17,Saturday Feb 28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
18,Saturday Feb 28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
19,Saturday Feb 28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
20,Saturday Feb 28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
21,Saturday Feb 28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
22,Saturday Feb 28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
23,Saturday Feb 28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
24,Saturday Feb 28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
25,Saturday Feb 28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
26,Sunday Mar 1,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
27,Sunday Mar 1,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
28,Sunday Mar 1,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
29,Sunday Mar 1,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
30,Saturday Feb 21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
31,Saturday Feb 21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
32,Saturday Feb 21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
33,Saturday Feb 21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
34,Saturday Feb 21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
35,Saturday Feb 21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
36,Saturday Feb 21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
37,Saturday Feb 21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
38,Saturday Feb 21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
39,Saturday Feb 21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
40,Saturday Feb 21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
41,Saturday Feb 21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
42,Saturday Feb 21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
43,Sunday Feb 22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
44,Sunday Feb 22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [55]:

matches_df.to_csv('matches_past2.csv', index=False)

In [28]:
matches = pd.read_csv('G:/My Drive/GitHubProjects/MLS/data/db_save/matches_past2.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'G:/My Drive/GitHubProjects/MLS/data/db_save/matches_past2.csv'

In [56]:
matches = matches_df

In [57]:
matches.head()

,date,home_team,away_team,home_score,away_score,match_id,link
1,Saturday Mar 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,Saturday Mar 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,Saturday Mar 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,Saturday Mar 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,Saturday Mar 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...

In [59]:
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

## remove 'days' from date column

for day in days:
    matches['date'] = matches['date'].str.replace(f'{day} ', '', regex=False)
    
matches

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\566388080.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = matches['date'].str.replace(f'{day} ', '', regex=False)

,date,home_team,away_team,home_score,away_score,match_id,link
1,Mar 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,Mar 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,Mar 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,Mar 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,Mar 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
6,Mar 7,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
7,Mar 7,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
8,Mar 7,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
9,Mar 7,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
10,Mar 7,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
11,Mar 7,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
12,Mar 7,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
13,Mar 8,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
14,Mar 8,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
15,Feb 28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
16,Feb 28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
17,Feb 28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
18,Feb 28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
19,Feb 28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
20,Feb 28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
21,Feb 28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
22,Feb 28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
23,Feb 28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
24,Feb 28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
25,Feb 28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
26,Mar 1,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
27,Mar 1,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
28,Mar 1,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
29,Mar 1,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
30,Feb 21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
31,Feb 21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
32,Feb 21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
33,Feb 21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
34,Feb 21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
35,Feb 21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
36,Feb 21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
37,Feb 21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
38,Feb 21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
39,Feb 21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
40,Feb 21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
41,Feb 21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
42,Feb 21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
43,Feb 22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
44,Feb 22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [60]:
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

### convert month abbreviations to numbers

for i, month in enumerate(months, start=1):
    matches['date'] = matches['date'].str.replace(month, str(i).zfill(2), regex=False)
matches.head()

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\3771870977.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = matches['date'].str.replace(month, str(i).zfill(2), regex=False)

,date,home_team,away_team,home_score,away_score,match_id,link
1,03 7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,03 7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,03 7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,03 7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,03 7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...

In [61]:
### add / for date formatting

matches['date'] = matches['date'].str.replace(' ', '/', regex=False)

matches.head()

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\3554812759.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = matches['date'].str.replace(' ', '/', regex=False)

,date,home_team,away_team,home_score,away_score,match_id,link
1,03/7,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,03/7,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,03/7,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,03/7,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,03/7,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...

In [62]:
### if there is no third part of the date, add the year 2025

matches['date'] = matches['date'].apply(lambda x: x if x.count('/') == 2 else f"{x}/2026")

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\1704861575.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = matches['date'].apply(lambda x: x if x.count('/') == 2 else f"{x}/2026")

In [63]:
matches.head()

,date,home_team,away_team,home_score,away_score,match_id,link
1,03/7/2026,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,03/7/2026,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,03/7/2026,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,03/7/2026,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,03/7/2026,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...

In [64]:
### if ',' present, remove it

matches['date'] = matches['date'].str.replace(',', '', regex=False)

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\460232259.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = matches['date'].str.replace(',', '', regex=False)

In [65]:
### convert to datetime

matches['date'] = pd.to_datetime(matches['date'], format='%m/%d/%Y')

C:\Users\diffe\AppData\Local\Temp\ipykernel_7820\301160750.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matches['date'] = pd.to_datetime(matches['date'], format='%m/%d/%Y')

In [66]:
matches.head()

,date,home_team,away_team,home_score,away_score,match_id,link
1,2026-03-07,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,2026-03-07,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,2026-03-07,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,2026-03-07,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,2026-03-07,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...

In [67]:
matches

,date,home_team,away_team,home_score,away_score,match_id,link
1,2026-03-07,NYC,ORL,5,0,8865ae2a,https://www.mlssoccer.com/competitions/mls-reg...
2,2026-03-07,DC,MIA,1,2,0c956f37,https://www.mlssoccer.com/competitions/mls-reg...
3,2026-03-07,ATL,RSL,2,3,b0713dc5,https://www.mlssoccer.com/competitions/mls-reg...
4,2026-03-07,CLT,ATX,3,1,646c3889,https://www.mlssoccer.com/competitions/mls-reg...
5,2026-03-07,CLB,CHI,0,0,5291010f,https://www.mlssoccer.com/competitions/mls-reg...
6,2026-03-07,PHI,SJ,0,1,3991a1bb,https://www.mlssoccer.com/competitions/mls-reg...
7,2026-03-07,SKC,SD,0,1,f1fd2f24,https://www.mlssoccer.com/competitions/mls-reg...
8,2026-03-07,NSH,MIN,3,1,dbcc55cf,https://www.mlssoccer.com/competitions/mls-reg...
9,2026-03-07,STL,SEA,0,1,29662ef7,https://www.mlssoccer.com/competitions/mls-reg...
10,2026-03-07,COL,LA,4,1,e8e41c6d,https://www.mlssoccer.com/competitions/mls-reg...
11,2026-03-07,LAFC,DAL,1,0,ab677e15,https://www.mlssoccer.com/competitions/mls-reg...
12,2026-03-07,POR,VAN,1,4,679970bf,https://www.mlssoccer.com/competitions/mls-reg...
13,2026-03-08,RBNY,MTL,0,3,bc090e7f,https://www.mlssoccer.com/competitions/mls-reg...
14,2026-03-08,CIN,TOR,0,1,1d8589b6,https://www.mlssoccer.com/competitions/mls-reg...
15,2026-02-28,CHI,MTL,3,0,2677b200,https://www.mlssoccer.com/competitions/mls-reg...
16,2026-02-28,RBNY,NE,1,0,696e062e,https://www.mlssoccer.com/competitions/mls-reg...
17,2026-02-28,COL,POR,2,0,9932553a,https://www.mlssoccer.com/competitions/mls-reg...
18,2026-02-28,MIN,CIN,1,0,ccc1ebe1,https://www.mlssoccer.com/competitions/mls-reg...
19,2026-02-28,RSL,SEA,2,1,c123bdf2,https://www.mlssoccer.com/competitions/mls-reg...
20,2026-02-28,SJ,ATL,2,0,5924fd44,https://www.mlssoccer.com/competitions/mls-reg...
21,2026-02-28,DAL,NSH,0,0,19a7b817,https://www.mlssoccer.com/competitions/mls-reg...
22,2026-02-28,HOU,LAFC,0,2,a52dabed,https://www.mlssoccer.com/competitions/mls-reg...
23,2026-02-28,SKC,CLB,2,2,775e1f69,https://www.mlssoccer.com/competitions/mls-reg...
24,2026-02-28,VAN,TOR,3,0,68a62bb0,https://www.mlssoccer.com/competitions/mls-reg...
25,2026-02-28,LA,CLT,3,0,708a4133,https://www.mlssoccer.com/competitions/mls-reg...
26,2026-03-01,ATX,DC,1,0,ce9a56f3,https://www.mlssoccer.com/competitions/mls-reg...
27,2026-03-01,PHI,NYC,1,2,fdf75599,https://www.mlssoccer.com/competitions/mls-reg...
28,2026-03-01,ORL,MIA,2,4,99726934,https://www.mlssoccer.com/competitions/mls-reg...
29,2026-03-01,SD,STL,2,0,8317cb19,https://www.mlssoccer.com/competitions/mls-reg...
30,2026-02-21,STL,CLT,1,1,95ee8e18,https://www.mlssoccer.com/competitions/mls-reg...
31,2026-02-21,CIN,ATL,2,0,3fe21bbf,https://www.mlssoccer.com/competitions/mls-reg...
32,2026-02-21,DC,PHI,1,0,0c970002,https://www.mlssoccer.com/competitions/mls-reg...
33,2026-02-21,ORL,RBNY,1,2,36ada33a,https://www.mlssoccer.com/competitions/mls-reg...
34,2026-02-21,VAN,RSL,1,0,31608e02,https://www.mlssoccer.com/competitions/mls-reg...
35,2026-02-21,ATX,MIN,2,2,adfb093f,https://www.mlssoccer.com/competitions/mls-reg...
36,2026-02-21,DAL,TOR,3,2,f45d88a5,https://www.mlssoccer.com/competitions/mls-reg...
37,2026-02-21,HOU,CHI,2,1,ed610e2c,https://www.mlssoccer.com/competitions/mls-reg...
38,2026-02-21,NSH,NE,4,1,1a13ae26,https://www.mlssoccer.com/competitions/mls-reg...
39,2026-02-21,LAFC,MIA,3,0,b5d3f6dd,https://www.mlssoccer.com/competitions/mls-reg...
40,2026-02-21,POR,CLB,3,2,a2d28725,https://www.mlssoccer.com/competitions/mls-reg...
41,2026-02-21,SD,MTL,5,0,e138c719,https://www.mlssoccer.com/competitions/mls-reg...
42,2026-02-21,SJ,SKC,3,0,9a5ab6be,https://www.mlssoccer.com/competitions/mls-reg...
43,2026-02-22,LA,NYC,1,1,f6e2b863,https://www.mlssoccer.com/competitions/mls-reg...
44,2026-02-22,SEA,COL,2,0,890188eb,https://www.mlssoccer.com/competitions/mls-reg...

In [69]:
### subset df to match id and link

matches = matches_df[['match_id', 'link']]

matches

    match_id                                               link
1   8865ae2a  https://www.mlssoccer.com/competitions/mls-reg...
2   0c956f37  https://www.mlssoccer.com/competitions/mls-reg...
3   b0713dc5  https://www.mlssoccer.com/competitions/mls-reg...
4   646c3889  https://www.mlssoccer.com/competitions/mls-reg...
5   5291010f  https://www.mlssoccer.com/competitions/mls-reg...
6   3991a1bb  https://www.mlssoccer.com/competitions/mls-reg...
7   f1fd2f24  https://www.mlssoccer.com/competitions/mls-reg...
8   dbcc55cf  https://www.mlssoccer.com/competitions/mls-reg...
9   29662ef7  https://www.mlssoccer.com/competitions/mls-reg...
10  e8e41c6d  https://www.mlssoccer.com/competitions/mls-reg...
11  ab677e15  https://www.mlssoccer.com/competitions/mls-reg...
12  679970bf  https://www.mlssoccer.com/competitions/mls-reg...
13  bc090e7f  https://www.mlssoccer.com/competitions/mls-reg...
14  1d8589b6  https://www.mlssoccer.com/competitions/mls-reg...
15  2677b200  https://www.mlssoccer.com/competitions/mls-reg...
16  696e062e  https://www.mlssoccer.com/competitions/mls-reg...
17  9932553a  https://www.mlssoccer.com/competitions/mls-reg...
18  ccc1ebe1  https://www.mlssoccer.com/competitions/mls-reg...
19  c123bdf2  https://www.mlssoccer.com/competitions/mls-reg...
20  5924fd44  https://www.mlssoccer.com/competitions/mls-reg...
21  19a7b817  https://www.mlssoccer.com/competitions/mls-reg...
22  a52dabed  https://www.mlssoccer.com/competitions/mls-reg...
23  775e1f69  https://www.mlssoccer.com/competitions/mls-reg...
24  68a62bb0  https://www.mlssoccer.com/competitions/mls-reg...
25  708a4133  https://www.mlssoccer.com/competitions/mls-reg...
26  ce9a56f3  https://www.mlssoccer.com/competitions/mls-reg...
27  fdf75599  https://www.mlssoccer.com/competitions/mls-reg...
28  99726934  https://www.mlssoccer.com/competitions/mls-reg...
29  8317cb19  https://www.mlssoccer.com/competitions/mls-reg...
30  95ee8e18  https://www.mlssoccer.com/competitions/mls-reg...
31  3fe21bbf  https://www.mlssoccer.com/competitions/mls-reg...
32  0c970002  https://www.mlssoccer.com/competitions/mls-reg...
33  36ada33a  https://www.mlssoccer.com/competitions/mls-reg...
34  31608e02  https://www.mlssoccer.com/competitions/mls-reg...
35  adfb093f  https://www.mlssoccer.com/competitions/mls-reg...
36  f45d88a5  https://www.mlssoccer.com/competitions/mls-reg...
37  ed610e2c  https://www.mlssoccer.com/competitions/mls-reg...
38  1a13ae26  https://www.mlssoccer.com/competitions/mls-reg...
39  b5d3f6dd  https://www.mlssoccer.com/competitions/mls-reg...
40  a2d28725  https://www.mlssoccer.com/competitions/mls-reg...
41  e138c719  https://www.mlssoccer.com/competitions/mls-reg...
42  9a5ab6be  https://www.mlssoccer.com/competitions/mls-reg...
43  f6e2b863  https://www.mlssoccer.com/competitions/mls-reg...
44  890188eb  https://www.mlssoccer.com/competitions/mls-reg...

In [70]:
matches.to_csv('match_links_post020526.csv')

In [ ]:
from sqlalchemy import create_engine

db_string = 'mysql+pymysql://root:root@127.0.0.1:2022/MLS'

engine = create_engine(db_string)

In [ ]:
old_df = pd.read_sql("SELECT match_id AS old_hash, date, home_team_abbr, away_team_abbr FROM matches", engine)
new_df = matches.rename(columns={
    'home_team': 'home_team_abbr',
    'away_team': 'away_team_abbr'
})

## add 'new hash' column to new_df
new_df = new_df.assign(new_hash=lambda x: x.index + 1)

# make sure dates are datetime.date
old_df["date"] = pd.to_datetime(old_df["date"]).dt.date
new_df["date"] = pd.to_datetime(new_df["date"]).dt.date

In [ ]:
merged = (
    old_df
    .merge(new_df, on=["date", "home_team_abbr", "away_team_abbr"], how="right")
    [["old_hash", "new_hash", "date", "home_team_abbr", "away_team_abbr", 'home_score', 'away_score']]
)

In [ ]:
merged

In [ ]:
## percentage of nan in 'old_hash' column

nan_percentage = merged['old_hash'].isna().mean() * 100
nan_percentage

In [ ]:
## rename old hash to match_id and delete new_hash

merged = merged.rename(columns={'old_hash': 'match_id'}).drop(columns=['new_hash'])

In [ ]:
merged

In [ ]:
clean = lambda s: s.fillna("").str.lower().str.replace(r"\s+", "", regex=True)

merged["date"] = pd.to_datetime(merged["date"])

merged["slug"] = (
    clean(merged["home_team_abbr"])
    + "vs"
    + clean(merged["away_team_abbr"])
    + "-"
    + merged["date"].dt.strftime("%m-%d-%Y")
)

In [ ]:
import hashlib
def hash_match_ids(df: pd.DataFrame, col="slug", out_col="match_id_hash", length=8):
    if col not in df.columns:
        raise KeyError(f"Column '{col}' not found.")
    
    df = df.copy()
    df[out_col] = (
        df[col]
        .astype(str)
        .str.lower()
        .map(lambda x: hashlib.md5(x.encode()).hexdigest()[:length])
    )
    
    
    return df

In [ ]:
merged2 = hash_match_ids(merged, col="slug", out_col="match_id_hash", length=8)

In [ ]:
## remove 'slug' column

merged2 = merged2.drop(columns=['slug'], errors='ignore')

In [ ]:
merged2

In [ ]:
### if match_id nan, replace with match_id_hash

merged2['match_id'] = merged2.apply(
    lambda row: row['match_id_hash'] if pd.isna(row['match_id']) else row['match_id'],
    axis=1
)

merged2.drop(columns=['match_id_hash'], errors='ignore', inplace=True)

merged2

In [ ]:
merged2

In [ ]:
##check duplicates in merged2

merged2['match_id'].duplicated().sum()

## view duplicates

merged2[merged2['match_id'].duplicated(keep=False)].sort_values('match_id')

In [ ]:
## drop first occurrence of duplicates

merged2 = merged2[~merged2['match_id'].duplicated(keep='first')]

### rename to home_team_score and away_team_score

merged2 = merged2.rename(columns={'home_score': 'home_team_score', 'away_score': 'away_team_score'})

In [ ]:
merged2.to_sql('matches', engine, if_exists='append', index=False)